<h2>Impact (v0.64) - 'Impact (v0.64).ipynb'</h2>

<u><h4>Context</h4></u>

The aim of the 'Impact' notebooks are to explore economic impacts resulsting from the FEM outputs in the lead-up to Autumn 2026, taking foward outputs from the associated 'Trade' notebooks.

<u><h4>Version Documentation and Future Work</h4></u>

'v0.2' cleaned up the analysis code by introducing the cost intensity estimation functions that were previously in the 'inventories' notebooks. For example, the 'get_usd_per_tnm' function is included here and applied to voyages identified as relevant to each individual trade record. The NZF costs associated with each trade record are now evaluated like this. 'v0.3' introduced the exporter- and importer-side trade portfolios at an HS-digit 4 level of resolution. With this implemented, the matching algorithm is now be being evaluated using the cargo weight field rather than value, and the process will be being conducted at the HS-digit 4 level of resolution. Since we are now confident regarding the use of the Global Shipping Watch dataset for the purposes of matching HS codes with facilitating vessel types, we should then be in good shape to take the analysis forward using the results produced in this notebook. 'v0.3' also subsumed the 'inventories' notebooks. In 'v0.4' sought to include transport costs data from UNCTAD's Trade-and-Transport database. However, there are now concerns regarding this dataset as it is importer-side only, and therefore has odd looking exporter-side portfolios. Instead, it makes sense for us to utilise trade portfolios derived from UN Comtrade, where these are submitted with disaggregation by Transport Mode. Looking at the 16 countries of interest across African and Caribbean economies we're interested in the summer of 2026, 13 of these have a trade portfolio with MoT Breakdown available across at least one year within the last decade. Therefore this approach makes more sense, and 'v0.6' was amended to work with Comtrade import and export trade portfolios downloaded from the platform. 'v0.61' made use of the updated 'trade' notebooks that derive a new weight field using Value-to-Weight and Weight-to-Value ratios observed in the CEPII BACI datasets across 2017-23. In the case of Trinidad and Tobaogo, import volumes were around 65% higher under the WtV approach which corresponded to a 39% greater 2041 BAU impact from FEM costs, but this was slightly less for exports where the weighted WtV was 9% more but 2041 FEM costs under BAU were around 10% less. A new 'composite' weight field has been added in Trade (v0.61) which only introduces the VtW-derived values where 'netWgt' is observed to be zero, however this resulted in only a tiny increase in recorded weight of around 1% for Angola, whereas the full VtW-derived field was ~50% greater. 

'v0.62' makes use of a new 'transport cost' field derived using ad-valorem transport cost rates identified from UNCTAD's Trade-and-Transport database. With these, we can now introduce another results disaggregation that presents NZF costs relative to expected transport costs, which is then fully in-line with how impacts are expressed in UNCTAD's CIA Task 3 work. 'v0.63' includes an assessment of 'Cost Intensity' matching process (similar to CIF-FOB matching), plus metrics on 'fac_vessel_types' and 'average sea-distance' (introduced in Trade v0.63). 'v0.64' has been modified throughout to account for a new scenario, namely the 'Japan' proposal, plus to remove the 'Low-then-High' scenario. In terms of the Impact notebook, this remains the same as 'v0.63'.

In [1]:
# Import packages
import os
import ast
import base64
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', 250)
pd.set_option('display.max_rows', 250)
pd.options.mode.chained_assignment = None
from IPython.display import HTML
import matplotlib.pyplot as plt
import matplotlib.style
plt.style.use('seaborn-v0_8')

def voyages_analysis(voys):
    # Define a function to analyses key statistics from a given set of voyages, 'voys'.
    print("Number of Voyages found: {0}".format(voys.shape[0]))
    print("Total size of the fleet: {0} vessels".format(len(voys.imo.unique())))
    print("{0} vessel types contained in the dataset: {1}".format(len(voys.vessel_type.unique()), voys.vessel_type.unique()))
    print("Total transport work capacity: {0} million deadweight-tonne nautical miles".format(np.round(voys.dwtnm.sum() / 1e6, 1)))
    print("Total cargo transported: {0} tonnes".format(np.round(voys.tonnes.sum(), 1)))
    print("Total transport work: {0} million tonne nautical miles".format(np.round(voys.tnm.sum() / 1e6, 1)))
    print("Average build year of the fleet: {0}".format(int(np.round(voys.year_of_built.mean(), 0))))
    print("Total Energy Demands: {0} EJ".format(np.round(voys.energy_tj.sum(), 1)))
    print("Total CO2 produced: {0} tonnes".format(np.round(voys.co2_t.sum(), 1)))

def get_usd_per_dwtnm(voys, field_name):
    # Derive the deadweight-average of the cost intensity (per unit of cargo-carrying capacity) for the field 'field_name' in an input selection of voyages, 'voys'.
    return (voys[field_name].values * voys.deadweight.values).sum() / voys.deadweight.sum()
    
def get_usd_per_tnm(voys, field_name):
    # Derive the deadweight-average of the cost intensity (per unit of cargo-carried) for the field 'field_name' in an input selection of voyages, 'voys'.
    return (voys[field_name].values / voys.class_util.values * voys.tonnes.values).sum() / voys.tonnes.sum()

def download_link(df, title = "Download CSV file", filename = "data.csv"):
    csv = df.to_csv()
    b64 = base64.b64encode(csv.encode())
    payload = b64.decode()
    html = '<a download="{filename}" href="data:text/csv;base64,{payload}" target="_blank">{title}</a>'
    html = html.format(payload=payload,title=title,filename=filename)
    return HTML(html)

version = "v0.64"
input_dir = "/Users/apple/repos/PubEnv/2026_nzf_impact/"
voys_fem_dir = "/Users/apple/repos/datasets/ucl/fleet evolution model/2026 annex vi amendments (v0.2)/2. NZF Impact Costs for 2018 IMO IV Voyages/voys_fem_v0.2.csv"
output_dir = "/Users/apple/repos/PubEnv/2026_nzf_impact/impact/"
res_mlc = False

# 1. Set up the notebook

## 1.1 Let's set the country we're interested in and set up a results folder.

In [2]:
# Select one of our countries to work on...
iso_code = "270"
iso_country = "Gambia"
year = 2020
import_portfolio = "h4_ag6_by_sea_M.csv" # Imports, '_M' | Foreign Imports, '_FM' | Re-Imports, '_RM'
export_portfolio = "h4_ag6_by_sea_DX.csv" # Exports, '_X' | Domestic Exports, '_DX' | Re-exports, '_RX'
gdp = 1.810*1e9

# Create output Journey directory folder if necessary
os.makedirs(output_dir+"{0}/".format(iso_country)) if not os.path.exists(output_dir+"{0}/".format(iso_country)) else "Output directory already exists."
os.makedirs(output_dir+"{0}/results/".format(iso_country)) if not os.path.exists(output_dir+"{0}/results/".format(iso_country)) else "Output results folder already exists."

## 1.2 Voyages with FEM Results

In [3]:
voys_fem_d = {
    "source_iso":str, "source_iso_code":str, "source_iso_3":str, "source_iso_2":str, 
    "dest_iso_code":str, "dest_iso_code":str, "dest_iso_3":str, "dest_iso_2":str, 
    "source_region_code":str, "source_sub_region_code":str, "dest_region_code":str, "dest_sub_region_code":str, 
    "source_ldc":str, "source_sids":str, "dest_ldc":str, "dest_sids":str
}

voys_fem = pd.read_csv(voys_fem_dir, dtype=voys_fem_d)
voys_fem["dwtnm"] = voys_fem.deadweight * voys_fem.dist_travelled_ais
voys_fem["tonnes"] = voys_fem.deadweight * voys_fem.class_util
voys_fem["tnm"] = voys_fem.tonnes * voys_fem.dist_travelled_ais
voys_fem.loc[voys_fem.source_country == "Namibia", "source_iso_2"] = "NA"
voys_fem.loc[voys_fem.dest_country == "Namibia", "dest_iso_2"] = "NA"

countries_set = pd.Series(list(set(list(voys_fem.source_country.unique()) + list(voys_fem.dest_country.unique())))).sort_values()
print("Number of countries present in dataset: {0}.".format(len(countries_set)))
print("Number of IMO numbers present in dataset: {0}.".format(len(voys_fem.imo.unique())))
print("Total CO2 contained within the dataset: {0} million tonnes.".format(np.round(voys_fem.co2_t.sum() / 1e6, 1)))
print("Vessel types present in dataset: \n\n{0}\n".format(pd.Series(voys_fem.vessel_type.unique()).sort_values().values))
#print("\nCountries in dataset: \n\n", countries_set.values, "\n")
voys_fem.head(2)

Number of countries present in dataset: 207.
Number of IMO numbers present in dataset: 26132.
Total CO2 contained within the dataset: 544.7 million tonnes.
Vessel types present in dataset:

['Bulk carrier' 'Chemical tanker' 'Container' 'General cargo'
 'Liquefied gas tanker' 'Oil tanker' 'Refrigerated bulk' 'Vehicle']

,voy_idx,imo,mmsi,source_iso,source_iso_code,source_iso_3,source_iso_2,source_country,source_name,dest_iso,dest_iso_code,dest_iso_3,dest_iso_2,dest_country,dest_name,start_date,end_date,duration_hrs_voy,duration_hrs_stop,duration_hrs,dist_travelled_ais,foc_hfo_t_voy,foc_hfo_t_stop,foc_hfo_t,foc_mdo_t_voy,foc_mdo_t_stop,foc_mdo_t,foc_lng_t_voy,foc_lng_t_stop,foc_lng_t,foc_methanol_t_voy,foc_methanol_t_stop,foc_methanol_t,energy_tj_voy,energy_tj_stop,co2_t_voy,co2_t_stop,co2_t,source_region_code,source_region,source_sub_region_code,source_sub_region,source_income_wesp,source_ldc,source_sids,dest_region_code,dest_region,dest_sub_region_code,dest_sub_region,dest_income_wesp,dest_ldc,dest_sids,energy_tj,vessel_type,gross_tonnage,capacity_unit,deadweight,teu,gas_cap,passengers,cars,size_id,size_range,year_of_built,flag,engine_type,me_fuel,class_med_aer,class_util,bau35_usd_dwtnm_26,bau35_usd_dwtnm_29,bau35_usd_dwtnm_32,bau35_usd_dwtnm_35,bau35_usd_dwtnm_38,bau35_usd_dwtnm_41,bau35_usd_dwtnm_44,bau35_usd_dwtnm_47,bau35_usd_dwtnm_50,levy35_usd_dwtnm_26,levy35_usd_dwtnm_29,levy35_usd_dwtnm_32,levy35_usd_dwtnm_35,levy35_usd_dwtnm_38,levy35_usd_dwtnm_41,levy35_usd_dwtnm_44,levy35_usd_dwtnm_47,levy35_usd_dwtnm_50,asis35_usd_dwtnm_26,asis35_usd_dwtnm_29,asis35_usd_dwtnm_32,asis35_usd_dwtnm_35,asis35_usd_dwtnm_38,asis35_usd_dwtnm_41,asis35_usd_dwtnm_44,asis35_usd_dwtnm_47,asis35_usd_dwtnm_50,brazil35_usd_dwtnm_26,brazil35_usd_dwtnm_29,brazil35_usd_dwtnm_32,brazil35_usd_dwtnm_35,brazil35_usd_dwtnm_38,brazil35_usd_dwtnm_41,brazil35_usd_dwtnm_44,brazil35_usd_dwtnm_47,brazil35_usd_dwtnm_50,liscr35_usd_dwtnm_26,liscr35_usd_dwtnm_29,liscr35_usd_dwtnm_32,liscr35_usd_dwtnm_35,liscr35_usd_dwtnm_38,liscr35_usd_dwtnm_41,liscr35_usd_dwtnm_44,liscr35_usd_dwtnm_47,liscr35_usd_dwtnm_50,direct35_usd_dwtnm_26,direct35_usd_dwtnm_29,direct35_usd_dwtnm_32,direct35_usd_dwtnm_35,direct35_usd_dwtnm_38,direct35_usd_dwtnm_41,direct35_usd_dwtnm_44,direct35_usd_dwtnm_47,direct35_usd_dwtnm_50,dwtnm,bau35_usd_26,bau35_usd_29,bau35_usd_32,bau35_usd_35,bau35_usd_38,bau35_usd_41,bau35_usd_44,bau35_usd_47,bau35_usd_50,levy35_usd_26,levy35_usd_29,levy35_usd_32,levy35_usd_35,levy35_usd_38,levy35_usd_41,levy35_usd_44,levy35_usd_47,levy35_usd_50,asis35_usd_26,asis35_usd_29,asis35_usd_32,asis35_usd_35,asis35_usd_38,asis35_usd_41,asis35_usd_44,asis35_usd_47,asis35_usd_50,brazil35_usd_26,brazil35_usd_29,brazil35_usd_32,brazil35_usd_35,brazil35_usd_38,brazil35_usd_41,brazil35_usd_44,brazil35_usd_47,brazil35_usd_50,liscr35_usd_26,liscr35_usd_29,liscr35_usd_32,liscr35_usd_35,liscr35_usd_38,liscr35_usd_41,liscr35_usd_44,liscr35_usd_47,liscr35_usd_50,direct35_usd_26,direct35_usd_29,direct35_usd_32,direct35_usd_35,direct35_usd_38,direct35_usd_41,direct35_usd_44,direct35_usd_47,direct35_usd_50,tonnes,tnm
0,0,5034525,413781699,CNTAX,156,CHN,CN,China,Taixing,CNNKG,156,CHN,CN,China,Nanjing,2018-01-01 06:00:00,2018-01-01 19:00:00,13.0,1.0,14.0,62.568523,0.0,0.0,0.0,3.635661,0.338483,3.974144,0.0,0.0,0.0,0.0,0.0,0.0,0.155243,0.014453,11.655930,1.085176,12.741107,142,Asia,030,Eastern Asia,upp_mid_income,0,0,142,Asia,030,Eastern Asia,upp_mid_income,0,0,0.169696,Refrigerated bulk,3786.0,dwt,3881.0,NaN,NaN,NaN,NaN,2,2000-5999,1959.0,Panama,SSD,4,76.1,0.666667,0.03155,0.032676,0.032143,0.031676,0.031218,0.030769,0.03031,0.029878,0.029438,0.031576,0.052178,0.052414,0.05804,0.060001,0.059297,0.058435,0.058228,0.058319,0.031568,0.034644,0.036843,0.044726,0.049621,0.053882,0.057797,0.059065,0.057999,0.031568,0.032727,0.034529,0.040735,0.048178,0.055864,0.057447,0.058672,0.05942,0.031559,0.032699,0.033808,0.037977,0.040129,0.041837,0.043315,0.044697,0.045876,0.031559,0.033985,0.034896,0.036131,0.038297,0.039924,0.040606,0.041099,0.041463,242828.439338,7661.320668,7934.549945,7805.304846,7691.950531,7580.696290,7471.542086,7360.199865,7255.307537,7148.350725,7667.458038,12670.391275,12727.642802,14093.647297,14570.027623,14398.931835,14189.590704,14139.488873,14161.462401,7665.715352,8412.516422,8946.627490,10860.650719,12049.492896,13084.201484,14034.766615,14342.763237,14083.751009,7665.715352,7946.962662,8384.668998,9891.651071,11698.979626,13565.379532,13949.851660,14247.178318,14428.769963,7663.482493,7940.155892,8209.623358,9221.805242,9744.436151,10159.112402,10518.004352,10853.785659,11140.079340,7663.482493,8252.567981,8473.856677,8773.523328,9299.485535,9694.695953,9860.244395,9979.919640,10068.487874,2587.333335,161885.626306
1,1,5034525,413781699,CNNKG,156,CHN,CN,China,Nanjing,CNTOL,156,CHN,CN,China,Tongling,2018-01-01 20:00:00,2018-01-04 17:00:00,69.0,59.0,128.0,134.252308,0.0,0.0,0.0,21.355373,19.491146,40.846519,0.0,0.0,0.0,0.0,0.0,0.0,0.911874,0.832272,68.465325,62.488615,130.953940,142,Asia,030,Eastern Asia,upp_mid_income,0,0,142,Asia,030,Eastern Asia,upp_mid_income,0,0,1.744146,Refrigerated bulk,3786.0,dwt,3881.0,NaN,NaN,NaN,NaN,2,2000-5999,1959.0,Panama,SSD,4,76.1,0.666667,0.03155,0.032676,0.032143,0.031676,0.031218,0.030769,0.03031,0.029878,0.029438,0.031576,0.052178,0.052414,0.05804,0.060001,0.059297,0.058435,0.058228,0.058319,0.031568,0.034644,0.036843,0.044726,0.049621,0.053882,0.057797,0.059065,0.057999,0.031568,0.032727,0.034529,0.040735,0.048178,0.055864,0.057447,0.058672,0.05942,0.031559,0.032699,0.033808,0.037977,0.040129,0.041837,0.043315,0.044697,0.045876,0.031559,0.033985,0.034896,0.036131,0.038297,0.039924,0.040606,0.041099,0.041463,521033.206847,16438.776642,17025.040451,16747.721252,16504.498662,16265.782167,16031.571689,15792.666415,15567.600579,15338.105010,16451.945500,27186.661563,27309.505274,30240.519881,31262.681739,30895.564166,30446.384156,30338.881438,30386.029694,16448.206246,18050.605691,19196.639505,23303.529390,25854.409564,28074.567693,30114.180516,30775.044079,30219.285570,16448.206246,17051.674227,17990.853906,21224.361910,25102.318690,29107.023950,29931.979818,30569.949005,30959.587375,16443.415234,17037.069045,17615.261197,19787.084130,20908.485145,21798.249530,22568.318408,23288.799137,23903.095037,16443.415234,17707.406809,18182.222523,18825.212595,19953.761526,20801.758375,21156.973093,21413.758406,21603.797889,2587.333335,347355.471405

# 2. Let's consider Imports

## 2.1 Read-in Trade dataset

In [4]:
trade_im_d = {
    "reporterCode":"str", "partnerCode":"str", "partner2Code":"str", 
    "cmdCode":"str", "HS2":"str", "HS4":"str", "hs2":"str", "hs4":"str", "hs6":"str",
    "isic":"str", "sitc":"str", "gtap":"str", "cpc":"str"
}
if res_mlc == False:
    trade_im = pd.read_csv(input_dir+"trade/{0}/trade_im_dist_{1}.csv".format(iso_country, version), dtype=trade_im_d)
else:
    trade_im = pd.read_csv(input_dir+"trade/{0}/trade_im_mlc_{1}.csv".format(iso_country, version), dtype=trade_im_d)
trade_im['fac_vessel_types'] = [ast.literal_eval(x) for x in trade_im.fac_vessel_types.values]

print("Aggregate trade portfolio statistics for '{0}': \n".format(iso_country))
print("Number of trade records present in dataset: {0}".format(trade_im.shape[0]))
print("Number of partner countries present in dataset: {0}".format(len(trade_im.partnerCode.unique())))
print("Modes of transport present in dataset: {0}".format(trade_im.motDesc.unique()))
print("Total value within the dataset: US${0}m".format(np.round(trade_im.cifvalue.sum() / 1e6, 1)))
print("Total weight within the dataset: {0} million kilograms".format(np.round(trade_im.vol_kg_vtw.sum() / 1e6, 1)))

print("\nDistance to market: {0} nm (min) to {1} nm (max), {2} nm (observed mean)".format(
    round(trade_im.sea_dist_nm.min(), 1),
    round(trade_im.sea_dist_nm.max(), 1),
    round(trade_im.sea_dist_nm.mean(), 1)
))
print("Average distance to market (volume-weighted): {0} nm".format(
    round((trade_im.vol_kg_vtw / 1000 * trade_im.sea_dist_nm).sum() / (trade_im.vol_kg_vtw.sum() / 1000), 1)
))
print("Average distance to market (value-weighted): {0} nm".format(
    round((trade_im.cifvalue / 1000 * trade_im.sea_dist_nm).sum() / (trade_im.cifvalue.sum() / 1000), 1)
))
trade_im.head(2)

Aggregate trade portfolio statistics for 'Gambia':

Number of trade records present in dataset: 12429
Number of partner countries present in dataset: 110
Modes of transport present in dataset: ['Sea']
Total value within the dataset: US$524.2m
Total weight within the dataset: 1006.3 million kilograms

Distance to market: 95.1 nm (min) to 13593.1 nm (max), 5547.1 nm (observed mean)
Average distance to market (volume-weighted): 3371.2 nm
Average distance to market (value-weighted): 5349.8 nm

,trade_idx,reporterCode,reporterDesc,partnerCode,partnerDesc,partner2Code,partner2Desc,flowDesc,motDesc,HS6_desc,HS6,qtyUnitAbbr,qty,netWgt,cifvalue,fobvalue,primaryValue,HS6_bilat_desc,HS2,HS2_desc,HS2_bilat_desc,HS4,HS4_desc,HS4_bilat_desc,hs2,hs4,hs6,hs6_description,eora_desc,isic,isic_desc,sitc,sitc_desc,gtap,gtap_desc,cpc,cpc_desc,usd_per_kg,kg_per_usd_cepii,_trade_im_vtw_hs4_m,kg_per_usd_netWgt,vol_kg_vtw,vol_kg_vtw_comp,fac_vessel_types,fac_vessel_types_str,sea_dist_km,sea_dist_nm,tnm
0,0,270,Gambia,036,Australia,000,World,Import,Sea,630130 | Blankets (other than,630130,kg,70.0,70.0,10.070,0,10.070,Australia | 630130 | Blankets (other than,63,"63 | Textiles, made up ar","Australia | 63 | Textiles, made up ar",6301,6301 | Blankets and travell,Australia | 6301 | Blankets and travell,63,6301,630130,"Blankets (excl. electric) & travelling rugs, o...",Textiles and Wearing Apparel,1721,"Manufacture of made-up textile articles, excep...",65832,Blankets & travelling rugs (other than electri...,27,TEX - Textiles,2711,Blankets and travelling rugs (except electric ...,5.5002,0.1818,both,6.951341,1.830726,70.0,[Container],['Container'],18631.0,11576.763101,21.193881
1,1,270,Gambia,699,India,000,World,Import,Sea,630130 | Blankets (other than,630130,kg,35.0,35.0,25.185,0,25.185,India | 630130 | Blankets (other than,63,"63 | Textiles, made up ar","India | 63 | Textiles, made up ar",6301,6301 | Blankets and travell,India | 6301 | Blankets and travell,63,6301,630130,"Blankets (excl. electric) & travelling rugs, o...",Textiles and Wearing Apparel,1721,"Manufacture of made-up textile articles, excep...",65832,Blankets & travelling rugs (other than electri...,27,TEX - Textiles,2711,Blankets and travelling rugs (except electric ...,5.5002,0.1818,both,1.389716,4.578633,35.0,[Container],['Container'],12880.0,8003.258480,36.643983

## 2.2 Derive Internationally Arriving Voyages

In [5]:
# International Arrivals
int_arr_voys = voys_fem[(voys_fem.dest_country == iso_country) & (voys_fem.source_country != iso_country)].reset_index(drop=True)
int_arr_voys.to_csv(output_dir + "{0}/int_arr_voys_{1}.csv".format(iso_country, version), index=False)
int_dep_voys = voys_fem[(voys_fem.source_country == iso_country) & (voys_fem.dest_country != iso_country)].reset_index(drop=True)
int_dep_voys.to_csv(output_dir + "{0}/int_dep_voys_{1}.csv".format(iso_country, version), index=False)
voyages_analysis(int_arr_voys)
int_arr_voys.head(2)

Number of Voyages found: 209
Total size of the fleet: 93 vessels
4 vessel types contained in the dataset: ['Bulk carrier' 'General cargo' 'Container' 'Chemical tanker']
Total transport work capacity: 4138.1 million deadweight-tonne nautical miles
Total cargo transported: 3147053.0 tonnes
Total transport work: 2599.8 million tonne nautical miles
Average build year of the fleet: 2002
Total Energy Demands: 718.7 EJ
Total CO2 produced: 55063.3 tonnes

,voy_idx,imo,mmsi,source_iso,source_iso_code,source_iso_3,source_iso_2,source_country,source_name,dest_iso,dest_iso_code,dest_iso_3,dest_iso_2,dest_country,dest_name,start_date,end_date,duration_hrs_voy,duration_hrs_stop,duration_hrs,dist_travelled_ais,foc_hfo_t_voy,foc_hfo_t_stop,foc_hfo_t,foc_mdo_t_voy,foc_mdo_t_stop,foc_mdo_t,foc_lng_t_voy,foc_lng_t_stop,foc_lng_t,foc_methanol_t_voy,foc_methanol_t_stop,foc_methanol_t,energy_tj_voy,energy_tj_stop,co2_t_voy,co2_t_stop,co2_t,source_region_code,source_region,source_sub_region_code,source_sub_region,source_income_wesp,source_ldc,source_sids,dest_region_code,dest_region,dest_sub_region_code,dest_sub_region,dest_income_wesp,dest_ldc,dest_sids,energy_tj,vessel_type,gross_tonnage,capacity_unit,deadweight,teu,gas_cap,passengers,cars,size_id,size_range,year_of_built,flag,engine_type,me_fuel,class_med_aer,class_util,bau35_usd_dwtnm_26,bau35_usd_dwtnm_29,bau35_usd_dwtnm_32,bau35_usd_dwtnm_35,bau35_usd_dwtnm_38,bau35_usd_dwtnm_41,bau35_usd_dwtnm_44,bau35_usd_dwtnm_47,bau35_usd_dwtnm_50,levy35_usd_dwtnm_26,levy35_usd_dwtnm_29,levy35_usd_dwtnm_32,levy35_usd_dwtnm_35,levy35_usd_dwtnm_38,levy35_usd_dwtnm_41,levy35_usd_dwtnm_44,levy35_usd_dwtnm_47,levy35_usd_dwtnm_50,asis35_usd_dwtnm_26,asis35_usd_dwtnm_29,asis35_usd_dwtnm_32,asis35_usd_dwtnm_35,asis35_usd_dwtnm_38,asis35_usd_dwtnm_41,asis35_usd_dwtnm_44,asis35_usd_dwtnm_47,asis35_usd_dwtnm_50,brazil35_usd_dwtnm_26,brazil35_usd_dwtnm_29,brazil35_usd_dwtnm_32,brazil35_usd_dwtnm_35,brazil35_usd_dwtnm_38,brazil35_usd_dwtnm_41,brazil35_usd_dwtnm_44,brazil35_usd_dwtnm_47,brazil35_usd_dwtnm_50,liscr35_usd_dwtnm_26,liscr35_usd_dwtnm_29,liscr35_usd_dwtnm_32,liscr35_usd_dwtnm_35,liscr35_usd_dwtnm_38,liscr35_usd_dwtnm_41,liscr35_usd_dwtnm_44,liscr35_usd_dwtnm_47,liscr35_usd_dwtnm_50,direct35_usd_dwtnm_26,direct35_usd_dwtnm_29,direct35_usd_dwtnm_32,direct35_usd_dwtnm_35,direct35_usd_dwtnm_38,direct35_usd_dwtnm_41,direct35_usd_dwtnm_44,direct35_usd_dwtnm_47,direct35_usd_dwtnm_50,dwtnm,bau35_usd_26,bau35_usd_29,bau35_usd_32,bau35_usd_35,bau35_usd_38,bau35_usd_41,bau35_usd_44,bau35_usd_47,bau35_usd_50,levy35_usd_26,levy35_usd_29,levy35_usd_32,levy35_usd_35,levy35_usd_38,levy35_usd_41,levy35_usd_44,levy35_usd_47,levy35_usd_50,asis35_usd_26,asis35_usd_29,asis35_usd_32,asis35_usd_35,asis35_usd_38,asis35_usd_41,asis35_usd_44,asis35_usd_47,asis35_usd_50,brazil35_usd_26,brazil35_usd_29,brazil35_usd_32,brazil35_usd_35,brazil35_usd_38,brazil35_usd_41,brazil35_usd_44,brazil35_usd_47,brazil35_usd_50,liscr35_usd_26,liscr35_usd_29,liscr35_usd_32,liscr35_usd_35,liscr35_usd_38,liscr35_usd_41,liscr35_usd_44,liscr35_usd_47,liscr35_usd_50,direct35_usd_26,direct35_usd_29,direct35_usd_32,direct35_usd_35,direct35_usd_38,direct35_usd_41,direct35_usd_44,direct35_usd_47,direct35_usd_50,tonnes,tnm
0,17532,8122957,357704000,ESCEU,724,ESP,ES,Spain,Ceuta,GMBJL,270,GMB,GM,Gambia,Banjul,2018-06-13 01:00:00,2018-06-18 17:00:00,136.0,426.0,562.0,1627.530641,79.354797,0.017060,79.371857,5.4670,23.2837,28.7507,0.0,0.0,0.0,0.0,0.0,0.0,3.423504,0.994900,264.638040,74.700666,339.338706,150,Europe,039,Southern Europe,high_income,0,0,002,Africa,202,Sub-Saharan Africa,low_income,1,0,4.418404,Bulk carrier,11080.0,dwt,18002.0,NaN,NaN,NaN,NaN,2,10000-34999,1982.0,Panama,SSD,1,7.3,0.630252,0.005685,0.00585,0.005772,0.005704,0.005636,0.00557,0.005503,0.005439,0.005375,0.005679,0.008743,0.008434,0.009194,0.010062,0.010741,0.009622,0.009117,0.00874,0.00568,0.006101,0.006289,0.00738,0.008266,0.010126,0.009534,0.009233,0.008792,0.00568,0.005823,0.006054,0.006899,0.007901,0.010534,0.010072,0.010112,0.009959,0.005682,0.005836,0.005984,0.00657,0.006821,0.007489,0.008556,0.008416,0.008515,0.005682,0.006024,0.006142,0.006304,0.006598,0.006811,0.006887,0.006936,0.006966,2.929881e+07,166565.372484,171407.966302,169117.283820,167108.242513,165136.421970,163201.821543,161228.441676,159369.376850,157473.722018,166393.610442,256158.277553,247112.373649,269381.772861,294805.169192,314696.873061,281916.754264,267128.235407,256072.455278,166409.546729,178764.018745,184255.679838,216228.431003,242192.640443,296677.843059,279334.432095,270517.481579,257607.914574,166409.546729,170614.455834,177388.096189,202123.259064,231497.218743,308643.436588,295099.212832,296259.623286,291800.434155,166486.836997,171000.504731,175335.842655,192504.074000,199836.080526,219432.177253,250688.173918,246570.275782,249479.731918,166486.836997,176492.022571,179944.109126,184708.226592,193308.052770,199549.598918,201793.284708,203223.675044,204104.280567,11345.798322,1.846563e+07
1,17534,8122957,357704000,ESAGP,724,ESP,ES,Spain,Malaga,GMBJL,270,GMB,GM,Gambia,Banjul,2018-07-16 18:00:00,2018-07-23 10:00:00,160.0,58.0,218.0,1694.689872,80.027136,0.001843,80.028979,6.7948,2.6537,9.4485,0.0,0.0,0.0,0.0,0.0,0.0,3.507229,0.113387,270.988631,8.513501,279.502132,150,Europe,039,Southern Europe,high_income,0,0,002,Africa,202,Sub-Saharan Africa,low_income,1,0,3.620616,Bulk carrier,11080.0,dwt,18002.0,NaN,NaN,NaN,NaN,2,10000-34999,1982.0,Panama,SSD,1,7.3,0.630252,0.005685,0.00585,0.005772,0.005704,0.005636,0.00557,0.005503,0.005439,0.005375,0.005679,0.008743,0.008434,0.009194,0.010062,0.010741,0.009622,0.009117,0.00874,0.00568,0.006101,0.006289,0.00738,0.008266,0.010126,0.009534,0.009233,0.008792,0.00568,0.005823,0.006054,0.006899,0.007901,0.010534,0.010072,0.010112,0.009959,0.005682,0.005836,0.005984,0.00657,0.006821,0.007489,0.008556,0.008416,0.008515,0.005682,0.006024,0.006142,0.006304,0.006598,0.006811,0.006887,0.006936,0.006966,3.050781e+07,173438.608502,178481.029511,176095.823172,174003.879790,171950.693068,169936.262330,167881.451939,165945.673742,163971.795670,173259.758786,266728.519575,257309.341013,280497.675743,306970.155691,327682.680679,293549.906826,278151.147203,266639.155888,173276.352676,186140.625744,191858.897460,225150.988063,252186.597499,308920.104500,290861.026437,281680.248908,268237.975137,173276.352676,177654.775233,184707.926439,210463.773324,241049.834622,321379.452206,307276.332893,308484.627098,303841.431779,173356.832289,178056.754243,182570.987699,200447.657444,208082.215518,228486.935285,261032.694875,256744.873751,259774.387126,173356.832289,183774.876795,187369.411959,192330.118328,201284.811992,207783.912392,210120.182743,211609.597414,212526.540679,11345.798322,1.922761e+07

## 2.3 Evaluate NZF Costs

In [6]:
years=["26", "29", "32", "35", "38", "41", "44", "47", "50"]
vess_types_not_found_in_inventories, vess_types_not_found_in_global_voys, hs_codes_not_mapped_to_HS, cost_int_match_desc, cost_int_match_desc_bool = [], [], [], [], False

for year in years:

    print("Processing game year 20{0}".format(year))

    # Setup columns for policy costs per bilateral goods trade.
    bau_usd, levy_usd, asis_usd, brazil_usd, liscr_usd, direct_usd = [], [], [], [], [], []
    
    for trade_idx, trade in trade_im.iterrows():

        # initiate selected voyages table as empty dataframe to begin
        int_arr_voys_vess = pd.DataFrame()

        # 3. If no facilitating vessel types were picked up for the HS code, take from full primary int. inv. voyages dataset, otherwise move on...
        if 'all' in trade.fac_vessel_types:
            hs_codes_not_mapped_to_HS.append(trade.HS4_desc)
            int_arr_voys_vess = int_arr_voys
            cost_int_match_desc.append("3. Primary Int. Inv. without Vess Type") if cost_int_match_desc_bool == False else None

        else:
            # 1. If possible, derive subset of voyages associated with the unique vessel type.
            int_arr_voys_vess = int_arr_voys[(int_arr_voys.vessel_type.isin(trade.fac_vessel_types))]    
            
            if int_arr_voys_vess.shape[0] > 0:
                cost_int_match_desc.append("1. Primary Int. Inv. with Vess Type") if cost_int_match_desc_bool == False else None
                
            else:
                # 2. Finally, if no voyages are found as the vessel type doesn't appear in the country's shipping inventories, also take from full voyages dataset filtered for those vessel types instead.
                int_arr_voys_vess = voys_fem[(voys_fem.vessel_type.isin(trade.fac_vessel_types))]

                if int_arr_voys_vess.shape[0] > 0:
                    cost_int_match_desc.append("2. Global Inv. with Vess Type") if cost_int_match_desc_bool == False else None
                    [vess_types_not_found_in_inventories.append(trade.fac_vessel_types[i]) for i in range(len(trade.fac_vessel_types))]

                else:
                    # 4. Use full global voyage dataset as a back-up
                    int_arr_voys_vess = voys_fem
                    cost_int_match_desc.append("4. Global Inv. without Vess Type.") if cost_int_match_desc_bool == False else None
                    [vess_types_not_found_in_global_voys.append(trade.fac_vessel_types[i]) for i in range(len(trade.fac_vessel_types))]

        # Add cost intensities associated with the subset of voyages by vessel type, assuming 50% of NZF costs are borne by the importer.
        bau_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "bau35_usd_dwtnm_"+year))
        levy_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "levy35_usd_dwtnm_"+year))
        asis_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "asis35_usd_dwtnm_"+year))
        brazil_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "brazil35_usd_dwtnm_"+year))
        liscr_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "liscr35_usd_dwtnm_"+year))
        direct_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_arr_voys_vess, "direct35_usd_dwtnm_"+year))
    
    if cost_int_match_desc_bool == False:
        trade_im["cost_int_match_desc"] = cost_int_match_desc
    cost_int_match_desc_bool = True
    
    trade_im["bau_usd_"+year] = bau_usd
    trade_im["levy_usd_"+year] = levy_usd
    trade_im["asis_usd_"+year] = asis_usd
    trade_im["brazil_usd_"+year] = brazil_usd
    trade_im["liscr_usd_"+year] = liscr_usd
    trade_im["direct_usd_"+year] = direct_usd

print("Inventory voyages table used for the following vessel types: \n\n{0}\n".format(pd.Series(vess_types_not_found_in_inventories).unique()))
print("Global voyages table used for the following vessel types found: \n\n{0}\n".format(pd.Series(vess_types_not_found_in_global_voys).unique()))
print("Global voyages table used for the following commodities as no 'facilitating vessel types' were identified: \n\n{0}\n".format(pd.Series(hs_codes_not_mapped_to_HS).unique()))

print("\nNumber of trade records present in dataset: {0}".format(trade_im.shape[0]))
print("Number of partner countries present in dataset: {0}".format(len(trade_im.partnerCode.unique())))
print("\nTotal value of trade: US${0}m".format(np.round(trade_im.cifvalue.sum() / 1e6, 1)))
print("Total weight within the dataset: {0} million kilograms".format(np.round(trade_im.vol_kg_vtw.sum() / 1e6, 1)))

print("\nDistance to market: {0} nm (min) to {1} nm (max), {2} nm (observed mean)".format(
    round(trade_im.sea_dist_nm.min(), 1),
    round(trade_im.sea_dist_nm.max(), 1),
    round(trade_im.sea_dist_nm.mean(), 1)
))
print("Average distance to market (volume-weighted): {0} nm".format(
    round((trade_im.vol_kg_vtw / 1000 * trade_im.sea_dist_nm).sum() / (trade_im.vol_kg_vtw.sum() / 1000), 1)
))
print("Average distance to market (value-weighted): {0} nm".format(
    round((trade_im.cifvalue / 1000 * trade_im.sea_dist_nm).sum() / (trade_im.cifvalue.sum() / 1000), 1)
))

print("\n\nTotal FEM costs in 2041...\n")
print("BAU: US${0}m ({1}% ad-val)".format(
    np.round(trade_im.bau_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.bau_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))
print("Levy: US${0}m ({1}% ad-val)".format(
    np.round(trade_im.levy_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.levy_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))
print("'as-is': US${0}m ({1}% ad-val)".format(
    np.round(trade_im.asis_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.asis_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))
print("Brazil: US${0}m ({1}% ad-val)".format(
    np.round(trade_im.brazil_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.brazil_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))
print("LISCR: US${0}m ({1}% ad-val)".format(
    np.round(trade_im.liscr_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.liscr_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))
print("Direct: US${0}m ({1}% ad-val)".format(
    np.round(trade_im.direct_usd_41.sum() / 1e6, 1),
    round(100 * trade_im.direct_usd_41.sum() / trade_im.cifvalue.sum(), 1)
))

trade_im_agg = trade_im.groupby(["cost_int_match_desc"]).agg({"vol_kg_vtw":"sum", "cifvalue":"sum"}).reset_index().sort_values(by="vol_kg_vtw", ascending=False).reset_index(drop=True)
trade_im_agg["vol_kg_vtw_pct"] = round(100 * trade_im_agg.vol_kg_vtw / trade_im_agg.vol_kg_vtw.sum(), 1)
trade_im_agg["cifvalue_pct"] = round(100 * trade_im_agg.cifvalue / trade_im_agg.cifvalue.sum(), 1)
print("Most prominent 'cost intensity match' types...\n\n{0}\n".format(
    trade_im_agg[["cost_int_match_desc", "vol_kg_vtw_pct", "cifvalue_pct"]].head(5)
))
trade_im_agg_2 = trade_im.groupby(["fac_vessel_types_str", "cost_int_match_desc"]).agg({"vol_kg_vtw":"sum", "cifvalue":"sum"}).reset_index().sort_values(by="vol_kg_vtw", ascending=False).reset_index(drop=True)
trade_im_agg_2["vol_kg_vtw_pct"] = round(100 * trade_im_agg_2.vol_kg_vtw / trade_im_agg_2.vol_kg_vtw.sum(), 1)
trade_im_agg_2["cifvalue_pct"] = round(100 * trade_im_agg_2.cifvalue / trade_im_agg_2.cifvalue.sum(), 1)
print("Most prominent 'facilitating vessel types' and their 'cost intensity match' types...")
display(trade_im_agg_2[["fac_vessel_types_str", "cost_int_match_desc", "vol_kg_vtw_pct", "cifvalue_pct"]].head(5))

trade_im_na = trade_im[(trade_im[["vol_kg_vtw", "primaryValue", "HS2", "HS6", "sea_dist_nm", "tnm", "bau_usd_26"]].isnull().any(axis=1)) | (trade_im.fac_vessel_types.str.len() == 0)]
trade_im = trade_im[(~trade_im[["vol_kg_vtw", "primaryValue", "HS2", "HS6", "sea_dist_nm", "tnm", "bau_usd_26"]].isnull().any(axis=1)) | (~trade_im.fac_vessel_types.str.len() == 0)]
print("Rows with NA: ${0} ({1}%)\n".format(trade_im_na.primaryValue.sum(), round(100 * trade_im_na.primaryValue.sum() / trade_im.primaryValue.sum(), 1)))

trade_im.to_csv(output_dir + "{0}/impact_im_{1}.csv".format(iso_country, version), index=False)
trade_im.head(2)

Processing game year 2026
Processing game year 2029
Processing game year 2032
Processing game year 2035
Processing game year 2038
Processing game year 2041
Processing game year 2044
Processing game year 2047
Processing game year 2050
Inventory voyages table used for the following vessel types:

['Vehicle' 'Oil tanker' 'Ro-Ro' 'Liquefied gas tanker']

Global voyages table used for the following vessel types found:

['Ro-Ro' 'Other liquids tankers']

Global voyages table used for the following commodities as no 'facilitating vessel types' were identified:

['6310 | Rags; used or new, s' '6704 | Wigs, false beards, '
 '6907 | Ceramic flags and pa' '6914 | Ceramic articles; n.'
 '3307 | Perfumery, cosmetic ' '3402 | Organic surface-acti'
 '3603 | Safety fuses; detona' '3606 | Ferro-cerium and oth'
 '3808 | Insecticides, rodent' '3812 | Prepared rubber acce'
 '8716 | Trailers and semi-tr' '8803 | nan' '8903 | Yachts and other ves'
 '9006 | Cameras, photographi' '3822 | Reagents; diagnostic'
 '3824 | Prepared binders for' '7019 | Glass fibres (includ'
 '7104 | Stones; synthetic or' '3907 | Polyacetals, other p'
 '7229 | Wire of other alloy ' '0305 | Fish, dried, salted '
 '0403 | Yogurt; buttermilk, ' '0410 | Animal products; ins'
 '0802 | Nuts (excluding coco' '9114 | Clock or watch parts'
 '9209 | Musical instrument p' '9401 | Seats (not those of '
 '9403 | Furniture and parts ' '3926 | Articles of plastics'
 '0910 | Ginger, saffron, tum' '4011 | New pneumatic tyres,'
 '9027 | Instruments and appa' '4015 | Articles of apparel '
 '9405 | Luminaires and light' '9406 | Buildings; prefabric'
 '4401 | Fuel wood, in logs, ' '4403 | Wood in the rough, w'
 '4407 | Wood sawn or chipped' '9508 | Travelling circuses '
 '9701 | Paintings, drawings ' '9702 | Engravings, prints a'
 '9703 | Sculptures and statu' '9706 | Antiques; of an age '
 '7326 | Iron or steel; artic' '4412 | Plywood, veneered pa'
 '1008 | Buckwheat, millet an' '7419 | Copper; articles the'
 '7616 | Aluminium; articles ' '4414 | Wooden frames; for p'
 "4418 | Builders' joinery an" '4419 | Tableware and kitche'
 '4421 | Wooden articles n.e.' '4602 | Basketwork, wickerwo'
 '8215 | Cutlery; spoons, for' '8311 | Wires, rods, tubes, '
 '8419 | Machinery, plant (no' '8424 | Mechanical appliance'
 '1509 | Olive oil and its fr' '1510 | Vegetable oils; oils'
 '8432 | Agricultural, hortic' '8456 | Machine-tools; for w'
 '8459 | Machine-tools; (incl' '8460 | Machine-tools; for d'
 '8462 | Machine-tools (inclu' '8473 | Machinery; parts and'
 '1704 | Sugar confectionery ' '1806 | Chocolate and other '
 '1905 | Bread, pastry, cakes' '8514 | Industrial or labora'
 '8517 | Telephone sets, incl' '8525 | Transmission apparat'
 '8528 | Monitors and project' '8541 | Semiconductor device'
 '8548 | Electrical parts of ' '8701 | Tractors; (other tha'
 '8487 | Machinery parts; not' '4823 | Paper, paperboard, c'
 '4905 | Maps and hydrographi' '4911 | Printed matter, n.e.'
 '5007 | Woven fabrics of sil' '5703 | Carpets and other te'
 '5802 | Fabrics; terry towel' '4420 | Wood marquetry and i'
 '4504 | Agglomerated cork (w' '4707 | Waste and scrap of p'
 '2009 | Fruit or nut juices ' '2106 | Food preparations no'
 '2202 | Waters, including mi' '2309 | Preparations of a ki'
 '2518 | Dolomite, whether or' '2530 | Mineral substances n'
 '3002 | Human blood; animal ' '3006 | Pharmaceutical goods'
 '6201 | Overcoats, car-coats' '6117 | Clothing accessories'
 "6202 | Coats; women's or gi" '3215 | Ink; printing, writi'
 '0306 | Crustaceans; in shel' '2812 | Halides and halide o'
 '3105 | Fertilizers; mineral']


Number of trade records present in dataset: 12429
Number of partner countries present in dataset: 110

Total value of trade: US$524.2m
Total weight within the dataset: 1006.3 million kilograms

Distance to market: 95.1 nm (min) to 13593.1 nm (max), 5547.1 nm (observed mean)
Average distance to market (volume-weighted): 3371.2 nm
Average distance to market (value-weighted): 5349.8 nm


Total FEM costs in 2041...

BAU: US$14.4m (2.8% ad-val)
Levy: US$31.4m (6.0% ad-val)
'as-is': US$30.1m (5.7% ad-val)
Brazil: US$30.7m (5.8% ad-val)
LISCR: US$20.6m (3.9% ad-val)
Direct: US$19.5m (3.7% ad-val)
Most prominent 'cost intensity match' types...

                      cost_int_match_desc  vol_kg_vtw_pct  cifvalue_pct
0     1. Primary Int. Inv. with Vess Type            87.3          75.8
1           2. Global Inv. with Vess Type            12.2          22.3
2  3. Primary Int. Inv. without Vess Type             0.5           1.8
3       4. Global Inv. without Vess Type.             0.0           0.0

Most prominent 'facilitating vessel types' and their 'cost intensity match' types...

,fac_vessel_types_str,cost_int_match_desc,vol_kg_vtw_pct,cifvalue_pct
0,['Container'],1. Primary Int. Inv. with Vess Type,64.7,54.0
1,['Oil tanker'],2. Global Inv. with Vess Type,11.8,14.6
2,"['Container', 'Bulk carrier']",1. Primary Int. Inv. with Vess Type,10.5,9.2
3,['Bulk carrier'],1. Primary Int. Inv. with Vess Type,8.9,9.3
4,"['Container', 'General cargo']",1. Primary Int. Inv. with Vess Type,1.5,1.1

Rows with NA: $0.0 (0.0%)

,trade_idx,reporterCode,reporterDesc,partnerCode,partnerDesc,partner2Code,partner2Desc,flowDesc,motDesc,HS6_desc,HS6,qtyUnitAbbr,qty,netWgt,cifvalue,fobvalue,primaryValue,HS6_bilat_desc,HS2,HS2_desc,HS2_bilat_desc,HS4,HS4_desc,HS4_bilat_desc,hs2,hs4,hs6,hs6_description,eora_desc,isic,isic_desc,sitc,sitc_desc,gtap,gtap_desc,cpc,cpc_desc,usd_per_kg,kg_per_usd_cepii,_trade_im_vtw_hs4_m,kg_per_usd_netWgt,vol_kg_vtw,vol_kg_vtw_comp,fac_vessel_types,fac_vessel_types_str,sea_dist_km,sea_dist_nm,tnm,cost_int_match_desc,bau_usd_26,levy_usd_26,asis_usd_26,brazil_usd_26,liscr_usd_26,direct_usd_26,bau_usd_29,levy_usd_29,asis_usd_29,brazil_usd_29,liscr_usd_29,direct_usd_29,bau_usd_32,levy_usd_32,asis_usd_32,brazil_usd_32,liscr_usd_32,direct_usd_32,bau_usd_35,levy_usd_35,asis_usd_35,brazil_usd_35,liscr_usd_35,direct_usd_35,bau_usd_38,levy_usd_38,asis_usd_38,brazil_usd_38,liscr_usd_38,direct_usd_38,bau_usd_41,levy_usd_41,asis_usd_41,brazil_usd_41,liscr_usd_41,direct_usd_41,bau_usd_44,levy_usd_44,asis_usd_44,brazil_usd_44,liscr_usd_44,direct_usd_44,bau_usd_47,levy_usd_47,asis_usd_47,brazil_usd_47,liscr_usd_47,direct_usd_47,bau_usd_50,levy_usd_50,asis_usd_50,brazil_usd_50,liscr_usd_50,direct_usd_50
0,0,270,Gambia,036,Australia,000,World,Import,Sea,630130 | Blankets (other than,630130,kg,70.0,70.0,10.070,0,10.070,Australia | 630130 | Blankets (other than,63,"63 | Textiles, made up ar","Australia | 63 | Textiles, made up ar",6301,6301 | Blankets and travell,Australia | 6301 | Blankets and travell,63,6301,630130,"Blankets (excl. electric) & travelling rugs, o...",Textiles and Wearing Apparel,1721,"Manufacture of made-up textile articles, excep...",65832,Blankets & travelling rugs (other than electri...,27,TEX - Textiles,2711,Blankets and travelling rugs (except electric ...,5.5002,0.1818,both,6.951341,1.830726,70.0,[Container],['Container'],18631.0,11576.763101,21.193881,1. Primary Int. Inv. with Vess Type,0.097054,0.096869,0.096888,0.096888,0.096971,0.096971,0.101633,0.181492,0.111114,0.104230,0.104531,0.106946,0.099467,0.177174,0.117554,0.108055,0.105466,0.110396,0.097568,0.194458,0.146227,0.128019,0.118267,0.115136,0.095703,0.206205,0.169512,0.157681,0.126492,0.123490,0.093874,0.210252,0.202174,0.204699,0.136122,0.129760,0.092008,0.205835,0.195292,0.213015,0.161267,0.132178,0.090250,0.182192,0.191053,0.199782,0.146734,0.133743,0.088457,0.167496,0.169811,0.204845,0.170747,0.134671
1,1,270,Gambia,699,India,000,World,Import,Sea,630130 | Blankets (other than,630130,kg,35.0,35.0,25.185,0,25.185,India | 630130 | Blankets (other than,63,"63 | Textiles, made up ar","India | 63 | Textiles, made up ar",6301,6301 | Blankets and travell,India | 6301 | Blankets and travell,63,6301,630130,"Blankets (excl. electric) & travelling rugs, o...",Textiles and Wearing Apparel,1721,"Manufacture of made-up textile articles, excep...",65832,Blankets & travelling rugs (other than electri...,27,TEX - Textiles,2711,Blankets and travelling rugs (except electric ...,5.5002,0.1818,both,1.389716,4.578633,35.0,[Container],['Container'],12880.0,8003.258480,36.643983,1. Primary Int. Inv. with Vess Type,0.167806,0.167486,0.167519,0.167519,0.167661,0.167661,0.175723,0.313797,0.192115,0.180213,0.180732,0.184908,0.171978,0.306331,0.203250,0.186825,0.182349,0.190874,0.168693,0.336215,0.252825,0.221343,0.204482,0.199069,0.165470,0.356525,0.293085,0.272628,0.218703,0.213512,0.162307,0.363524,0.349556,0.353922,0.235354,0.224354,0.159080,0.355886,0.337657,0.368300,0.278829,0.228534,0.156041,0.315007,0.330328,0.345421,0.253701,0.231239,0.152942,0.289599,0.293601,0.354175,0.295219,0.232845

## 2.4 Create Results Tables

### 2.4.1 Total Costs per Scenario

In [7]:
print("\nTotal FEM costs by scenario (US$m)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        np.round(trade_im["bau_usd_{0}".format(year)].sum(), 2),
        np.round(trade_im["levy_usd_{0}".format(year)].sum(), 2),
        np.round(trade_im["asis_usd_{0}".format(year)].sum(), 2),
        np.round(trade_im["brazil_usd_{0}".format(year)].sum(), 2),
        np.round(trade_im["liscr_usd_{0}".format(year)].sum(), 2),
        np.round(trade_im["direct_usd_{0}".format(year)].sum(), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_total_costs_usd_{1}.csv".format(iso_country, version), index=False)
display(df)

if res_mlc == True:
    print("\nTotal FEM costs by scenario (% ciffob)...\n")
    d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * trade_im["bau_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
            round(100 * trade_im["levy_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
            round(100 * trade_im["asis_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
            round(100 * trade_im["brazil_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
            round(100 * trade_im["liscr_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
            round(100 * trade_im["direct_usd_{0}".format(year)].sum() / trade_im.TandT_ciffob.sum(), 2),
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_im_total_costs_pct_ciffob_{1}.csv".format(iso_country, version), index=False)
    display(df)

print("\nTotal FEM costs by scenario (% cif)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * trade_im["bau_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
        round(100 * trade_im["levy_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
        round(100 * trade_im["asis_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
        round(100 * trade_im["brazil_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
        round(100 * trade_im["liscr_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
        round(100 * trade_im["direct_usd_{0}".format(year)].sum() / trade_im.cifvalue.sum(), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_total_costs_pct_cif_{1}.csv".format(iso_country, version), index=False)
display(df)

if res_mlc == True:
    print("\nTotal FEM costs by scenario (% fob)...\n")
    d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * trade_im["bau_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * trade_im["levy_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * trade_im["asis_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * trade_im["brazil_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * trade_im["liscr_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * trade_im["direct_usd_{0}".format(year)].sum() / trade_im.TandT_fobvalue.sum(), 2)
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_im_total_costs_pct_fob_{1}.csv".format(iso_country, version), index=False)
    display(df)

print("\nTotal FEM costs by scenario (% gdp)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * trade_im["bau_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_im["levy_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_im["asis_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_im["brazil_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_im["liscr_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_im["direct_usd_{0}".format(year)].sum() / gdp, 3),
    ]}
    d = d | d_temp

df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_total_costs_pct_gdp_{1}.csv".format(iso_country, version), index=False)
display(df)

Total FEM costs by scenario (US$m)...

,Scenario,2029,2032,2035,2038,2041,2044,2047,2050
0,BAU,15528091.65,15219415.67,14949202.81,14684071.28,14423795.38,14158295.09,13908332.95,13653053.31
1,Levy,26884899.42,26206693.22,28726354.69,30742402.93,31428243.51,30324141.82,27144514.52,25119376.79
2,'as-is',16815354.12,17707337.55,21788186.94,25153140.17,30083532.41,28965447.65,28308241.96,25455968.76
3,Brazil,15821456.30,16413048.88,19315230.98,23511157.80,30656862.14,31436013.35,29904213.07,30356679.11
4,LISCR,15870507.50,16058381.77,17942098.93,19071351.98,20602499.16,24211318.99,22454816.57,25354311.04
5,Direct,16268948.16,16752468.78,17422640.48,18608033.12,19495621.82,19833245.77,20053756.44,20207979.40

Total FEM costs by scenario (% cif)...

  Scenario  2029  2032  2035  2038  2041  2044  2047  2050
0      BAU  2.96  2.90  2.85  2.80  2.75  2.70  2.65  2.60
1     Levy  5.13  5.00  5.48  5.86  6.00  5.78  5.18  4.79
2  'as-is'  3.21  3.38  4.16  4.80  5.74  5.53  5.40  4.86
3   Brazil  3.02  3.13  3.68  4.49  5.85  6.00  5.70  5.79
4    LISCR  3.03  3.06  3.42  3.64  3.93  4.62  4.28  4.84
5   Direct  3.10  3.20  3.32  3.55  3.72  3.78  3.83  3.86

Total FEM costs by scenario (% gdp)...

  Scenario   2029   2032   2035   2038   2041   2044   2047   2050
0      BAU  0.858  0.841  0.826  0.811  0.797  0.782  0.768  0.754
1     Levy  1.485  1.448  1.587  1.698  1.736  1.675  1.500  1.388
2  'as-is'  0.929  0.978  1.204  1.390  1.662  1.600  1.564  1.406
3   Brazil  0.874  0.907  1.067  1.299  1.694  1.737  1.652  1.677
4    LISCR  0.877  0.887  0.991  1.054  1.138  1.338  1.241  1.401
5   Direct  0.899  0.926  0.963  1.028  1.077  1.096  1.108  1.116

### 2.4.2 Costs per Scenario relative to BAU

In [8]:
print("\nTotal FEM costs by scenario (US$m)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    
    d_temp = {"20{0}".format(year): [
        np.round((trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_usd_bau_{1}.csv".format(iso_country, version), index=False)
display(df)

print("\nTotal change in FEM costs by scenario (% bau)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    
    d_temp = {"20{0}".format(year): [
        round((100 * (trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im["bau_usd_{0}".format(year)].sum()), 2)
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_pct_bau_{1}.csv".format(iso_country, version), index=False)
display(df)

if res_mlc == True:
    print("\nTotal FEM costs by scenario (% ciffob)...\n")
    d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * (trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_ciffob.sum(), 2),
            round(100 * (trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_ciffob.sum(), 2),
            round(100 * (trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_ciffob.sum(), 2),
            round(100 * (trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_ciffob.sum(), 2),
            round(100 * (trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_ciffob.sum(), 2)
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_pct_ciffob_{1}.csv".format(iso_country, version), index=False)
    display(df)

print("\nTotal FEM costs by scenario (% cif)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * (trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.cifvalue.sum(), 2),
        round(100 * (trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.cifvalue.sum(), 2),
        round(100 * (trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.cifvalue.sum(), 2),
        round(100 * (trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.cifvalue.sum(), 2),
        round(100 * (trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.cifvalue.sum(), 2)
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_pct_cif_{1}.csv".format(iso_country, version), index=False)
display(df)

if res_mlc == True:
    print("\nTotal FEM costs by scenario (% fob)...\n")
    d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * (trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * (trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * (trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * (trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_fobvalue.sum(), 2),
            round(100 * (trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / trade_im.TandT_fobvalue.sum(), 2)
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_pct_fob_{1}.csv".format(iso_country, version), index=False)
    display(df)
    
print("\nTotal FEM costs by scenario (% gdp)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * (trade_im["levy_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_im["direct_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_im["asis_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_im["brazil_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_im["liscr_usd_{0}".format(year)].sum() - trade_im["bau_usd_{0}".format(year)].sum()) / gdp, 3)
    ]}
    d = d | d_temp

df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_im_costs_to_bau_pct_gdp_{1}.csv".format(iso_country, version), index=False)
display(df)

Total FEM costs by scenario (US$m)...

,Scenario,2029,2032,2035,2038,2041,2044,2047,2050
0,Levy,11356807.77,10987277.56,13777151.88,16058331.66,17004448.13,16165846.72,13236181.57,11466323.48
1,'as-is',1287262.46,2487921.88,6838984.13,10469068.90,15659737.03,14807152.55,14399909.01,11802915.45
2,Brazil,293364.65,1193633.21,4366028.17,8827086.53,16233066.76,17277718.26,15995880.12,16703625.80
3,LISCR,342415.85,838966.10,2992896.12,4387280.70,6178703.78,10053023.90,8546483.62,11701257.72
4,Direct,740856.51,1533053.11,2473437.67,3923961.85,5071826.44,5674950.68,6145423.49,6554926.08

Total change in FEM costs by scenario (% bau)...

  Scenario   2029   2032   2035    2038    2041    2044    2047    2050
0     Levy  73.14  72.19  92.16  109.36  117.89  114.18   95.17   83.98
1  'as-is'   4.77  10.07  16.55   26.72   35.16   40.08   44.19   48.01
2   Brazil   8.29  16.35  45.75   71.30  108.57  104.58  103.53   86.45
3    LISCR   1.89   7.84  29.21   60.11  112.54  122.03  115.01  122.34
4   Direct   2.21   5.51  20.02   29.88   42.84   71.00   61.45   85.70

Total FEM costs by scenario (% cif)...

  Scenario  2029  2032  2035  2038  2041  2044  2047  2050
0     Levy  2.17  2.10  2.63  3.06  3.24  3.08  2.53  2.19
1  'as-is'  0.14  0.29  0.47  0.75  0.97  1.08  1.17  1.25
2   Brazil  0.25  0.47  1.30  2.00  2.99  2.82  2.75  2.25
3    LISCR  0.06  0.23  0.83  1.68  3.10  3.30  3.05  3.19
4   Direct  0.07  0.16  0.57  0.84  1.18  1.92  1.63  2.23

Total FEM costs by scenario (% gdp)...

  Scenario   2029   2032   2035   2038   2041   2044   2047   2050
0     Levy  0.627  0.607  0.761  0.887  0.939  0.893  0.731  0.633
1  'as-is'  0.041  0.085  0.137  0.217  0.280  0.314  0.340  0.362
2   Brazil  0.071  0.137  0.378  0.578  0.865  0.818  0.796  0.652
3    LISCR  0.016  0.066  0.241  0.488  0.897  0.955  0.884  0.923
4   Direct  0.019  0.046  0.165  0.242  0.341  0.555  0.472  0.646

# 3. Let's consider Exports

## 3.1 Read-in Trade dataset

In [9]:
trade_ex_d = {
    "reporterCode":"str", "partnerCode":"str", "partner2Code":"str", 
    "cmdCode":"str", "HS2":"str", "HS4":"str", "hs2":"str", "hs4":"str", "hs6":"str",
    "isic":"str", "sitc":"str", "gtap":"str", "cpc":"str"
}
if res_mlc == False:
    trade_ex = pd.read_csv(input_dir+"trade/{0}/trade_ex_dist_{1}.csv".format(iso_country, version), dtype=trade_ex_d)
else:
    trade_ex = pd.read_csv(input_dir+"trade/{0}/trade_ex_mlc_{1}.csv".format(iso_country, version), dtype=trade_ex_d)
trade_ex['fac_vessel_types'] = [ast.literal_eval(x) for x in trade_ex.fac_vessel_types.values]

print("Aggregate trade portfolio statistics for '{0}': \n".format(iso_country))
print("Number of trade records present in dataset: {0}".format(trade_ex.shape[0]))
print("Number of partner countries present in dataset: {0}".format(len(trade_ex.partnerCode.unique())))
print("Modes of transport present in dataset: {0}".format(trade_ex.motDesc.unique()))
print("Total value within the dataset: US${0}m".format(np.round(trade_ex.fobvalue.sum() / 1e6, 1)))
print("Total weight within the dataset: {0} million kilograms".format(np.round(trade_ex.vol_kg_vtw.sum() / 1e6, 1)))

print("\nDistance to market: {0} nm (min) to {1} nm (max), {2} nm (observed mean)".format(
    round(trade_ex.sea_dist_nm.min(), 1),
    round(trade_ex.sea_dist_nm.max(), 1),
    round(trade_ex.sea_dist_nm.mean(), 1)
))
print("Average distance to market (volume-weighted): {0} nm".format(
    round((trade_ex.vol_kg_vtw / 1000 * trade_ex.sea_dist_nm).sum() / (trade_ex.vol_kg_vtw.sum() / 1000), 1)
))
print("Average distance to market (value-weighted): {0} nm".format(
    round((trade_ex.fobvalue / 1000 * trade_ex.sea_dist_nm).sum() / (trade_ex.fobvalue.sum() / 1000), 1)
))
trade_ex.head(2)

Aggregate trade portfolio statistics for 'Gambia':

Number of trade records present in dataset: 53
Number of partner countries present in dataset: 21
Modes of transport present in dataset: ['Sea']
Total value within the dataset: US$3.3m
Total weight within the dataset: 11.7 million kilograms

Distance to market: 93.8 nm (min) to 13104.1 nm (max), 6550.7 nm (observed mean)
Average distance to market (volume-weighted): 12311.6 nm
Average distance to market (value-weighted): 9727.1 nm

,trade_idx,reporterCode,reporterDesc,partnerCode,partnerDesc,partner2Code,partner2Desc,flowDesc,motDesc,HS6_desc,HS6,qtyUnitAbbr,qty,netWgt,cifvalue,fobvalue,primaryValue,HS6_bilat_desc,HS2,HS2_desc,HS2_bilat_desc,HS4,HS4_desc,HS4_bilat_desc,hs2,hs4,hs6,hs6_description,eora_desc,isic,isic_desc,sitc,sitc_desc,gtap,gtap_desc,cpc,cpc_desc,usd_per_kg,kg_per_usd_cepii,_trade_ex_vtw_hs4_m,kg_per_usd_netWgt,vol_kg_vtw,vol_kg_vtw_comp,fac_vessel_types,fac_vessel_types_str,sea_dist_km,sea_dist_nm,tnm
0,0,270,Gambia,704,Viet Nam,000,World,Domestic Export,Sea,"030191 | Fish; live, trout (S",30191,kg,557176.0,579757.0,0,22524.266,22524.266,"Viet Nam | 030191 | Fish; live, trout (S",03,03 | Fish and crustaceans,Viet Nam | 03 | Fish and crustaceans,0301,0301 | Fish; live,Viet Nam | 0301 | Fish; live,03,0301,030191,"Live trout (Salmo trutta, Oncorhynchus mykiss/...",Fishing,0500,"Fishing, operation of fish hatcheries and fish...",03411,"Fish, live",14,FSH - Fishing,0411,"Fish, live",9.0916,0.1100,both,25.739218,2477.669260,579757.000000,[Container],['Container'],17667.0,10977.761457,27199.262106
1,1,270,Gambia,156,China,000,World,Domestic Export,Sea,970300 | Sculptures and statu,970300,u,85973.0,0.0,0,58447.929,58447.929,China | 970300 | Sculptures and statu,97,97 | Works of art; collec,China | 97 | Works of art; collec,9703,9703 | Sculptures and statu,China | 9703 | Sculptures and statu,97,9703,970300,"Original sculptures & statuary, in any material",NaN,9214,"Dramatic arts, music and other arts activities",8963,"Original sculptures & statuary, in any material",42,OMF - Manufactures n.e.c.,3896,"Paintings, drawings and pastels; original engr...",151.1495,0.0066,both,0.000000,385.756331,385.756331,[all],['all'],20503.0,12739.969613,4914.523940

## 3.2 Derive Internationally Departing Voyages

In [10]:
# International Departures
int_arr_voys = voys_fem[(voys_fem.dest_country == iso_country) & (voys_fem.source_country != iso_country)].reset_index(drop=True)
int_arr_voys.to_csv(output_dir + "{0}/int_arr_voys_{1}.csv".format(iso_country, version), index=False)
int_dep_voys = voys_fem[(voys_fem.source_country == iso_country) & (voys_fem.dest_country != iso_country)].reset_index(drop=True)
int_dep_voys.to_csv(output_dir + "{0}/int_dep_voys_{1}.csv".format(iso_country, version), index=False)
voyages_analysis(int_dep_voys)
int_dep_voys.head(2)

Number of Voyages found: 206
Total size of the fleet: 92 vessels
4 vessel types contained in the dataset: ['Bulk carrier' 'General cargo' 'Container' 'Chemical tanker']
Total transport work capacity: 7572.1 million deadweight-tonne nautical miles
Total cargo transported: 3102584.5 tonnes
Total transport work: 4752.1 million tonne nautical miles
Average build year of the fleet: 2002
Total Energy Demands: 838.5 EJ
Total CO2 produced: 64433.5 tonnes

,voy_idx,imo,mmsi,source_iso,source_iso_code,source_iso_3,source_iso_2,source_country,source_name,dest_iso,dest_iso_code,dest_iso_3,dest_iso_2,dest_country,dest_name,start_date,end_date,duration_hrs_voy,duration_hrs_stop,duration_hrs,dist_travelled_ais,foc_hfo_t_voy,foc_hfo_t_stop,foc_hfo_t,foc_mdo_t_voy,foc_mdo_t_stop,foc_mdo_t,foc_lng_t_voy,foc_lng_t_stop,foc_lng_t,foc_methanol_t_voy,foc_methanol_t_stop,foc_methanol_t,energy_tj_voy,energy_tj_stop,co2_t_voy,co2_t_stop,co2_t,source_region_code,source_region,source_sub_region_code,source_sub_region,source_income_wesp,source_ldc,source_sids,dest_region_code,dest_region,dest_sub_region_code,dest_sub_region,dest_income_wesp,dest_ldc,dest_sids,energy_tj,vessel_type,gross_tonnage,capacity_unit,deadweight,teu,gas_cap,passengers,cars,size_id,size_range,year_of_built,flag,engine_type,me_fuel,class_med_aer,class_util,bau35_usd_dwtnm_26,bau35_usd_dwtnm_29,bau35_usd_dwtnm_32,bau35_usd_dwtnm_35,bau35_usd_dwtnm_38,bau35_usd_dwtnm_41,bau35_usd_dwtnm_44,bau35_usd_dwtnm_47,bau35_usd_dwtnm_50,levy35_usd_dwtnm_26,levy35_usd_dwtnm_29,levy35_usd_dwtnm_32,levy35_usd_dwtnm_35,levy35_usd_dwtnm_38,levy35_usd_dwtnm_41,levy35_usd_dwtnm_44,levy35_usd_dwtnm_47,levy35_usd_dwtnm_50,asis35_usd_dwtnm_26,asis35_usd_dwtnm_29,asis35_usd_dwtnm_32,asis35_usd_dwtnm_35,asis35_usd_dwtnm_38,asis35_usd_dwtnm_41,asis35_usd_dwtnm_44,asis35_usd_dwtnm_47,asis35_usd_dwtnm_50,brazil35_usd_dwtnm_26,brazil35_usd_dwtnm_29,brazil35_usd_dwtnm_32,brazil35_usd_dwtnm_35,brazil35_usd_dwtnm_38,brazil35_usd_dwtnm_41,brazil35_usd_dwtnm_44,brazil35_usd_dwtnm_47,brazil35_usd_dwtnm_50,liscr35_usd_dwtnm_26,liscr35_usd_dwtnm_29,liscr35_usd_dwtnm_32,liscr35_usd_dwtnm_35,liscr35_usd_dwtnm_38,liscr35_usd_dwtnm_41,liscr35_usd_dwtnm_44,liscr35_usd_dwtnm_47,liscr35_usd_dwtnm_50,direct35_usd_dwtnm_26,direct35_usd_dwtnm_29,direct35_usd_dwtnm_32,direct35_usd_dwtnm_35,direct35_usd_dwtnm_38,direct35_usd_dwtnm_41,direct35_usd_dwtnm_44,direct35_usd_dwtnm_47,direct35_usd_dwtnm_50,dwtnm,bau35_usd_26,bau35_usd_29,bau35_usd_32,bau35_usd_35,bau35_usd_38,bau35_usd_41,bau35_usd_44,bau35_usd_47,bau35_usd_50,levy35_usd_26,levy35_usd_29,levy35_usd_32,levy35_usd_35,levy35_usd_38,levy35_usd_41,levy35_usd_44,levy35_usd_47,levy35_usd_50,asis35_usd_26,asis35_usd_29,asis35_usd_32,asis35_usd_35,asis35_usd_38,asis35_usd_41,asis35_usd_44,asis35_usd_47,asis35_usd_50,brazil35_usd_26,brazil35_usd_29,brazil35_usd_32,brazil35_usd_35,brazil35_usd_38,brazil35_usd_41,brazil35_usd_44,brazil35_usd_47,brazil35_usd_50,liscr35_usd_26,liscr35_usd_29,liscr35_usd_32,liscr35_usd_35,liscr35_usd_38,liscr35_usd_41,liscr35_usd_44,liscr35_usd_47,liscr35_usd_50,direct35_usd_26,direct35_usd_29,direct35_usd_32,direct35_usd_35,direct35_usd_38,direct35_usd_41,direct35_usd_44,direct35_usd_47,direct35_usd_50,tonnes,tnm
0,17533,8122957,357704000,GMBJL,270,GMB,GM,Gambia,Banjul,ESAGP,724,ESP,ES,Spain,Malaga,2018-07-06 11:00:00,2018-07-12 08:00:00,141.0,106.0,247.0,1665.918136,61.201717,9.524807e-07,61.201718,5.7158,4.8230,10.5388,0.0,0.0,0.0,0.0,0.0,0.0,2.704374,0.205942,208.907001,15.462541,224.369542,002,Africa,202,Sub-Saharan Africa,low_income,1,0,150,Europe,039,Southern Europe,high_income,0,0,2.910316,Bulk carrier,11080.0,dwt,18002.0,NaN,NaN,NaN,NaN,2,10000-34999,1982.0,Panama,SSD,1,7.3,0.630252,0.005685,0.00585,0.005772,0.005704,0.005636,0.00557,0.005503,0.005439,0.005375,0.005679,0.008743,0.008434,0.009194,0.010062,0.010741,0.009622,0.009117,0.00874,0.00568,0.006101,0.006289,0.00738,0.008266,0.010126,0.009534,0.009233,0.008792,0.00568,0.005823,0.006054,0.006899,0.007901,0.010534,0.010072,0.010112,0.009959,0.005682,0.005836,0.005984,0.00657,0.006821,0.007489,0.008556,0.008416,0.008515,0.005682,0.006024,0.006142,0.006304,0.006598,0.006811,0.006887,0.006936,0.006966,2.998986e+07,170494.040353,175450.853246,173106.141943,171049.714700,169031.386124,167051.155549,165031.230869,163128.317504,161187.951108,170318.227072,262200.114337,252940.850648,275735.503531,301758.544786,322119.421189,288566.139293,273428.813370,262112.267828,170334.539238,182980.408058,188601.597349,221328.468763,247905.078931,303675.388180,285922.909590,276897.999463,263683.942993,170334.539238,174638.626768,181572.032523,206890.607413,236957.391356,315923.206292,302059.523840,303247.304132,298682.939040,170413.652501,175033.781146,179471.373835,197044.540959,204549.482699,224607.779669,256600.990966,252385.966675,255364.046239,170413.652501,180654.823806,184188.332456,189064.818026,197867.482646,204256.244038,206552.850169,208016.978181,208918.353966,11345.798322,1.890117e+07
1,17535,8122957,357704000,GMBJL,270,GMB,GM,Gambia,Banjul,TNLGN,788,TUN,TN,Tunisia,La Goulette,2018-07-25 20:00:00,2018-08-23 20:00:00,696.0,335.0,1031.0,2484.766056,76.179598,5.998311e-05,76.179658,33.5585,15.2425,48.8010,0.0,0.0,0.0,0.0,0.0,0.0,4.495368,0.650857,344.811820,48.867642,393.679462,002,Africa,202,Sub-Saharan Africa,low_income,1,0,002,Africa,015,Northern Africa,low_mid_income,0,0,5.146225,Bulk carrier,11080.0,dwt,18002.0,NaN,NaN,NaN,NaN,2,10000-34999,1982.0,Panama,SSD,1,7.3,0.630252,0.005685,0.00585,0.005772,0.005704,0.005636,0.00557,0.005503,0.005439,0.005375,0.005679,0.008743,0.008434,0.009194,0.010062,0.010741,0.009622,0.009117,0.00874,0.00568,0.006101,0.006289,0.00738,0.008266,0.010126,0.009534,0.009233,0.008792,0.00568,0.005823,0.006054,0.006899,0.007901,0.010534,0.010072,0.010112,0.009959,0.005682,0.005836,0.005984,0.00657,0.006821,0.007489,0.008556,0.008416,0.008515,0.005682,0.006024,0.006142,0.006304,0.006598,0.006811,0.006887,0.006936,0.006966,4.473076e+07,254296.891998,261690.124691,258192.918596,255125.696684,252115.300057,249161.727724,246148.950461,243310.699027,240416.585293,254034.661303,391079.207340,377268.742334,411267.639715,450081.773617,480450.621565,430404.911552,407827.143278,390948.181681,254058.991379,272920.677870,281304.847563,330117.941958,369757.740226,452940.802099,426462.456456,413001.536701,393292.381566,254058.991379,260478.664933,270820.044201,308583.445732,353428.941171,471208.784213,450530.692756,452302.302110,445494.416894,254176.991146,261068.049347,267686.849783,293897.747084,305091.589141,335009.130936,382727.949618,376441.116515,380883.010060,254176.991146,269452.000335,274722.332751,281995.754872,295125.188895,304654.215026,308079.670836,310263.460968,311607.889549,11345.798322,2.819165e+07

## 3.3 Evaluate NZF Costs

In [11]:
years=["26", "29", "32", "35", "38", "41", "44", "47", "50"]
vess_types_not_found_in_inventories, vess_types_not_found_in_global_voys, hs_codes_not_mapped_to_HS, cost_int_match_desc, cost_int_match_desc_bool = [], [], [], [], False

for year in years:

    print("Processing game year 20{0}".format(year))

    # Setup columns for policy costs per bilateral goods trade.
    bau_usd, levy_usd, asis_usd, brazil_usd, liscr_usd, direct_usd = [], [], [], [], [], []
    
    for trade_idx, trade in trade_ex.iterrows():

        # initiate selected voyages table as empty dataframe to begin
        int_dep_voys_vess = pd.DataFrame()

        # 3. If no facilitating vessel types were picked up for the HS code, take from full primary int. inv. voyages dataset, otherwise move on...
        if 'all' in trade.fac_vessel_types:
            hs_codes_not_mapped_to_HS.append(trade.HS4_desc)
            int_dep_voys_vess = int_dep_voys
            cost_int_match_desc.append("3. Primary Int. Inv. without Vess Type") if cost_int_match_desc_bool == False else None

        else:
            # 1. If possible, derive subset of voyages associated with the unique vessel type.
            int_dep_voys_vess = int_dep_voys[(int_dep_voys.vessel_type.isin(trade.fac_vessel_types))]    
            
            if int_dep_voys_vess.shape[0] > 0:
                cost_int_match_desc.append("1. Primary Int. Inv. with Vess Type") if cost_int_match_desc_bool == False else None
                
            else:
                # 2. Finally, if no voyages are found as the vessel type doesn't appear in the country's shipping inventories, also take from full voyages dataset filtered for those vessel types instead.
                int_dep_voys_vess = voys_fem[(voys_fem.vessel_type.isin(trade.fac_vessel_types))]
                
                if int_dep_voys_vess.shape[0] > 0:
                    cost_int_match_desc.append("2. Global Inv. with Vess Type") if cost_int_match_desc_bool == False else None
                    [vess_types_not_found_in_inventories.append(trade.fac_vessel_types[i]) for i in range(len(trade.fac_vessel_types))]

                else:
                    # 4. Use full global voyage dataset as a back-up
                    int_dep_voys_vess = voys_fem
                    cost_int_match_desc.append("4. Global Inv. without Vess Type.") if cost_int_match_desc_bool == False else None
                    [vess_types_not_found_in_global_voys.append(trade.fac_vessel_types[i]) for i in range(len(trade.fac_vessel_types))]
    
        # Add cost intensities associated with the subset of voyages by vessel type, assuming 50% of NZF costs are borne by the exporter.
        bau_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "bau35_usd_dwtnm_"+year))
        levy_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "levy35_usd_dwtnm_"+year))
        asis_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "asis35_usd_dwtnm_"+year))
        brazil_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "brazil35_usd_dwtnm_"+year))
        liscr_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "liscr35_usd_dwtnm_"+year))
        direct_usd.append(0.5 * trade.tnm * get_usd_per_tnm(int_dep_voys_vess, "direct35_usd_dwtnm_"+year))

    if cost_int_match_desc_bool == False:
        trade_ex["cost_int_match_desc"] = cost_int_match_desc
    cost_int_match_desc_bool = True

    trade_ex["bau_usd_"+year] = bau_usd
    trade_ex["levy_usd_"+year] = levy_usd
    trade_ex["asis_usd_"+year] = asis_usd
    trade_ex["brazil_usd_"+year] = brazil_usd
    trade_ex["liscr_usd_"+year] = liscr_usd
    trade_ex["direct_usd_"+year] = direct_usd
    
print("Inventory voyages table used for the following vessel types: \n\n{0}\n".format(pd.Series(vess_types_not_found_in_inventories).unique()))
print("Global voyages table used for the following vessel types found: \n\n{0}\n".format(pd.Series(vess_types_not_found_in_global_voys).unique()))
print("Global voyages table used for the following commodities as no 'facilitating vessel types' were identified: \n\n{0}\n".format(pd.Series(hs_codes_not_mapped_to_HS).unique()))

print()
print("Number of trade records present in dataset: {0}".format(trade_ex.shape[0]))
print("Number of partner countries present in dataset: {0}".format(len(trade_ex.partnerCode.unique())))
print("\nTotal value of trade: US${0}m".format(np.round(trade_ex.fobvalue.sum() / 1e6, 1)))
print("Total weight within the dataset: {0} million kilograms".format(np.round(trade_ex.vol_kg_vtw.sum() / 1e6, 1)))

print("\nDistance to market: {0} nm (min) to {1} nm (max), {2} nm (observed mean)".format(
    round(trade_ex.sea_dist_nm.min(), 1),
    round(trade_ex.sea_dist_nm.max(), 1),
    round(trade_ex.sea_dist_nm.mean(), 1)
))
print("Average distance to market (volume-weighted): {0} nm".format(
    round((trade_ex.vol_kg_vtw / 1000 * trade_ex.sea_dist_nm).sum() / (trade_ex.vol_kg_vtw.sum() / 1000), 1)
))
print("Average distance to market (value-weighted): {0} nm".format(
    round((trade_ex.fobvalue / 1000 * trade_ex.sea_dist_nm).sum() / (trade_ex.fobvalue.sum() / 1000), 1)
))

print("\n\nTotal FEM costs in 2041...\n")
print("BAU: US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.bau_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.bau_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))
print("Levy: US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.levy_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.levy_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))
print("'as-is': US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.asis_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.asis_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))
print("Brazil: US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.brazil_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.brazil_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))
print("LISCR: US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.liscr_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.liscr_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))
print("Direct: US${0}m ({1}% ad-val)".format(
    np.round(trade_ex.direct_usd_41.sum() / 1e6, 1),
    round(100 * trade_ex.direct_usd_41.sum() / trade_ex.fobvalue.sum(), 1)
))

trade_ex_agg = trade_ex.groupby(["cost_int_match_desc"]).agg({"vol_kg_vtw":"sum", "fobvalue":"sum"}).reset_index().sort_values(by="vol_kg_vtw", ascending=False).reset_index(drop=True)
trade_ex_agg["vol_kg_vtw_pct"] = round(100 * trade_ex_agg.vol_kg_vtw / trade_ex_agg.vol_kg_vtw.sum(), 1)
trade_ex_agg["fobvalue_pct"] = round(100 * trade_ex_agg.fobvalue / trade_ex_agg.fobvalue.sum(), 1)
print("Most prominent 'cost intensity match' types...\n\n{0}\n".format(
    trade_ex_agg[["cost_int_match_desc", "vol_kg_vtw_pct", "fobvalue_pct"]].head(5)
))
trade_ex_agg_2 = trade_ex.groupby(["fac_vessel_types_str", "cost_int_match_desc"]).agg({"vol_kg_vtw":"sum", "fobvalue":"sum"}).reset_index().sort_values(by="vol_kg_vtw", ascending=False).reset_index(drop=True)
trade_ex_agg_2["vol_kg_vtw_pct"] = round(100 * trade_ex_agg_2.vol_kg_vtw / trade_ex_agg_2.vol_kg_vtw.sum(), 1)
trade_ex_agg_2["fobvalue_pct"] = round(100 * trade_ex_agg_2.fobvalue / trade_ex_agg_2.fobvalue.sum(), 1)
print("Most prominent 'facilitating vessel types' and their 'cost intensity match' types...")
display(trade_ex_agg_2[["fac_vessel_types_str", "cost_int_match_desc", "vol_kg_vtw_pct", "fobvalue_pct"]].head(5))

trade_ex_na = trade_ex[(trade_ex[["vol_kg_vtw", "primaryValue", "HS2", "HS6", "sea_dist_nm", "tnm", "bau_usd_26"]].isnull().any(axis=1)) | (trade_ex.fac_vessel_types.str.len() == 0)]
trade_ex = trade_ex[(~trade_ex[["vol_kg_vtw", "primaryValue", "HS2", "HS6", "sea_dist_nm", "tnm", "bau_usd_26"]].isnull().any(axis=1)) | (~trade_ex.fac_vessel_types.str.len() == 0)]
print("Rows with NA: ${0} ({1}%)\n".format(trade_ex_na.primaryValue.sum(), round(100 * trade_ex_na.primaryValue.sum() / trade_ex.primaryValue.sum(), 1)))

trade_ex.to_csv(output_dir + "{0}/impact_ex_{1}.csv".format(iso_country, version), index=False)
trade_ex.head(2)

Processing game year 2026
Processing game year 2029
Processing game year 2032
Processing game year 2035
Processing game year 2038
Processing game year 2041
Processing game year 2044
Processing game year 2047
Processing game year 2050
Inventory voyages table used for the following vessel types:

[]

Global voyages table used for the following vessel types found:

[]

Global voyages table used for the following commodities as no 'facilitating vessel types' were identified:

['9703 | Sculptures and statu' '2106 | Food preparations no'
 '8548 | Electrical parts of ' '3402 | Organic surface-acti']


Number of trade records present in dataset: 53
Number of partner countries present in dataset: 21

Total value of trade: US$3.3m
Total weight within the dataset: 11.7 million kilograms

Distance to market: 93.8 nm (min) to 13104.1 nm (max), 6550.7 nm (observed mean)
Average distance to market (volume-weighted): 12311.6 nm
Average distance to market (value-weighted): 9727.1 nm


Total FEM costs in 2041...

BAU: US$0.6m (19.5% ad-val)
Levy: US$1.4m (43.6% ad-val)
'as-is': US$1.4m (41.9% ad-val)
Brazil: US$1.4m (42.4% ad-val)
LISCR: US$0.9m (28.3% ad-val)
Direct: US$0.9m (26.9% ad-val)
Most prominent 'cost intensity match' types...

                      cost_int_match_desc  vol_kg_vtw_pct  fobvalue_pct
0     1. Primary Int. Inv. with Vess Type            99.9          97.2
1  3. Primary Int. Inv. without Vess Type             0.1           2.8

Most prominent 'facilitating vessel types' and their 'cost intensity match' types...

,fac_vessel_types_str,cost_int_match_desc,vol_kg_vtw_pct,fobvalue_pct
0,['Container'],1. Primary Int. Inv. with Vess Type,99.4,93.3
1,"['Chemical tanker', 'Container']",1. Primary Int. Inv. with Vess Type,0.4,3.3
2,['Chemical tanker'],1. Primary Int. Inv. with Vess Type,0.1,0.5
3,['all'],3. Primary Int. Inv. without Vess Type,0.1,2.8
4,"['General cargo', 'Container']",1. Primary Int. Inv. with Vess Type,0.0,0.1

Rows with NA: $0.0 (0.0%)

,trade_idx,reporterCode,reporterDesc,partnerCode,partnerDesc,partner2Code,partner2Desc,flowDesc,motDesc,HS6_desc,HS6,qtyUnitAbbr,qty,netWgt,cifvalue,fobvalue,primaryValue,HS6_bilat_desc,HS2,HS2_desc,HS2_bilat_desc,HS4,HS4_desc,HS4_bilat_desc,hs2,hs4,hs6,hs6_description,eora_desc,isic,isic_desc,sitc,sitc_desc,gtap,gtap_desc,cpc,cpc_desc,usd_per_kg,kg_per_usd_cepii,_trade_ex_vtw_hs4_m,kg_per_usd_netWgt,vol_kg_vtw,vol_kg_vtw_comp,fac_vessel_types,fac_vessel_types_str,sea_dist_km,sea_dist_nm,tnm,cost_int_match_desc,bau_usd_26,levy_usd_26,asis_usd_26,brazil_usd_26,liscr_usd_26,direct_usd_26,bau_usd_29,levy_usd_29,asis_usd_29,brazil_usd_29,liscr_usd_29,direct_usd_29,bau_usd_32,levy_usd_32,asis_usd_32,brazil_usd_32,liscr_usd_32,direct_usd_32,bau_usd_35,levy_usd_35,asis_usd_35,brazil_usd_35,liscr_usd_35,direct_usd_35,bau_usd_38,levy_usd_38,asis_usd_38,brazil_usd_38,liscr_usd_38,direct_usd_38,bau_usd_41,levy_usd_41,asis_usd_41,brazil_usd_41,liscr_usd_41,direct_usd_41,bau_usd_44,levy_usd_44,asis_usd_44,brazil_usd_44,liscr_usd_44,direct_usd_44,bau_usd_47,levy_usd_47,asis_usd_47,brazil_usd_47,liscr_usd_47,direct_usd_47,bau_usd_50,levy_usd_50,asis_usd_50,brazil_usd_50,liscr_usd_50,direct_usd_50
0,0,270,Gambia,704,Viet Nam,000,World,Domestic Export,Sea,"030191 | Fish; live, trout (S",30191,kg,557176.0,579757.0,0,22524.266,22524.266,"Viet Nam | 030191 | Fish; live, trout (S",03,03 | Fish and crustaceans,Viet Nam | 03 | Fish and crustaceans,0301,0301 | Fish; live,Viet Nam | 0301 | Fish; live,03,0301,030191,"Live trout (Salmo trutta, Oncorhynchus mykiss/...",Fishing,0500,"Fishing, operation of fish hatcheries and fish...",03411,"Fish, live",14,FSH - Fishing,0411,"Fish, live",9.0916,0.1100,both,25.739218,2477.669260,579757.000000,[Container],['Container'],17667.0,10977.761457,27199.262106,1. Primary Int. Inv. with Vess Type,124.849179,124.611447,124.635689,124.635689,124.741772,124.741772,130.736987,233.429863,142.956886,134.073400,134.459782,137.571325,127.951889,227.889962,151.227292,138.997538,135.669926,142.008977,125.509221,250.078135,188.102343,164.676728,152.136310,148.104016,123.111807,265.198013,218.012362,202.823848,162.720107,158.847332,120.759648,270.372780,259.952916,263.180818,175.133415,166.912623,118.360338,264.694143,251.183526,274.002119,207.348506,170.021232,116.100017,234.324144,245.692806,256.929057,188.779635,172.034062,113.795209,215.420449,218.408475,263.638480,219.714963,173.227433
1,1,270,Gambia,156,China,000,World,Domestic Export,Sea,970300 | Sculptures and statu,970300,u,85973.0,0.0,0,58447.929,58447.929,China | 970300 | Sculptures and statu,97,97 | Works of art; collec,China | 97 | Works of art; collec,9703,9703 | Sculptures and statu,China | 9703 | Sculptures and statu,97,9703,970300,"Original sculptures & statuary, in any material",NaN,9214,"Dramatic arts, music and other arts activities",8963,"Original sculptures & statuary, in any material",42,OMF - Manufactures n.e.c.,3896,"Paintings, drawings and pastels; original engr...",151.1495,0.0066,both,0.000000,385.756331,385.756331,[all],['all'],20503.0,12739.969613,4914.523940,3. Primary Int. Inv. without Vess Type,22.801339,22.766785,22.770156,22.770156,22.785644,22.785644,23.715342,39.658778,25.482287,24.024365,24.078646,24.744176,23.282993,38.576534,26.823195,24.961637,24.477250,25.423136,22.903801,42.411244,32.329318,29.161140,27.268571,26.357286,22.531635,45.614008,37.373334,35.102611,28.777399,28.016711,22.166494,45.908751,44.107769,45.175419,30.936103,29.250918,21.794033,44.690943,42.933145,46.012807,36.080478,29.719483,21.443149,40.196318,41.827268,44.384117,34.051022,30.023572,21.085358,37.394230,37.914956,44.686353,37.432093,30.208399

## 3.4 Create Results Tables

### 3.4.1 Total Costs per Scenario

In [12]:
print("\nTotal FEM costs by scenario (US$m)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        np.round(trade_ex["bau_usd_{0}".format(year)].sum(), 2),
        np.round(trade_ex["levy_usd_{0}".format(year)].sum(), 2),
        np.round(trade_ex["asis_usd_{0}".format(year)].sum(), 2),
        np.round(trade_ex["brazil_usd_{0}".format(year)].sum(), 2),
        np.round(trade_ex["liscr_usd_{0}".format(year)].sum(), 2),
        np.round(trade_ex["direct_usd_{0}".format(year)].sum(), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_total_costs_usd_{1}.csv".format(iso_country, version), index=False)
display(df)


if res_mlc == True:
    print("\nTotal FEM costs by scenario (% ciffob)...\n")
    d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * trade_ex["bau_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * trade_ex["levy_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * trade_ex["asis_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * trade_ex["brazil_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * trade_ex["liscr_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * trade_ex["direct_usd_{0}".format(year)].sum() / trade_ex.TandT_ciffob.sum(), 2),
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_ex_total_costs_pct_ciffob_{1}.csv".format(iso_country, version), index=False)
    display(df)


if res_mlc == True:
    print("\nTotal FEM costs by scenario (% cif)...\n")
    d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * trade_ex["bau_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * trade_ex["levy_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * trade_ex["asis_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * trade_ex["brazil_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * trade_ex["liscr_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * trade_ex["direct_usd_{0}".format(year)].sum() / trade_ex.TandT_cifvalue.sum(), 2)
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_ex_total_costs_pct_cif_{1}.csv".format(iso_country, version), index=False)
    display(df)

    
print("\nTotal FEM costs by scenario (% fob)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * trade_ex["bau_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
        round(100 * trade_ex["levy_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
        round(100 * trade_ex["asis_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
        round(100 * trade_ex["brazil_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
        round(100 * trade_ex["liscr_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
        round(100 * trade_ex["direct_usd_{0}".format(year)].sum() / trade_ex.fobvalue.sum(), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_total_costs_pct_fob_{1}.csv".format(iso_country, version), index=False)
display(df)


print("\nTotal FEM costs by scenario (% gdp)...\n")
d = {"Scenario":["BAU", "Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * trade_ex["bau_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_ex["levy_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_ex["asis_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_ex["brazil_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_ex["liscr_usd_{0}".format(year)].sum() / gdp, 3),
        round(100 * trade_ex["direct_usd_{0}".format(year)].sum() / gdp, 3)
    ]}
    d = d | d_temp

df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_total_costs_pct_gdp_{1}.csv".format(iso_country, version), index=False)
display(df)

Total FEM costs by scenario (US$m)...

,Scenario,2029,2032,2035,2038,2041,2044,2047,2050
0,BAU,690228.97,675532.58,662643.12,649992.46,637580.59,624919.92,612992.67,600830.67
1,Levy,1232115.24,1202858.18,1320011.03,1399896.01,1427042.71,1397114.14,1236856.54,1137106.89
2,'as-is',754697.05,798365.76,992875.71,1150802.62,1372063.06,1325870.72,1296815.35,1152893.84
3,Brazil,707804.84,733812.78,869344.76,1070659.13,1389162.68,1446187.41,1356238.60,1391532.08
4,LISCR,709844.01,716258.33,803180.71,859010.72,924518.47,1094506.29,996650.15,1159704.01
5,Direct,726287.73,749702.89,781863.55,838552.99,881109.75,897511.53,908131.90,914429.26

Total FEM costs by scenario (% fob)...

  Scenario   2029   2032   2035   2038   2041   2044   2047   2050
0      BAU  21.09  20.64  20.25  19.86  19.48  19.10  18.73  18.36
1     Levy  37.65  36.76  40.34  42.78  43.61  42.69  37.80  34.75
2  'as-is'  23.06  24.40  30.34  35.17  41.93  40.52  39.63  35.23
3   Brazil  21.63  22.42  26.57  32.72  42.45  44.19  41.44  42.52
4    LISCR  21.69  21.89  24.54  26.25  28.25  33.45  30.46  35.44
5   Direct  22.19  22.91  23.89  25.62  26.92  27.43  27.75  27.94

Total FEM costs by scenario (% gdp)...

  Scenario   2029   2032   2035   2038   2041   2044   2047   2050
0      BAU  0.038  0.037  0.037  0.036  0.035  0.035  0.034  0.033
1     Levy  0.068  0.066  0.073  0.077  0.079  0.077  0.068  0.063
2  'as-is'  0.042  0.044  0.055  0.064  0.076  0.073  0.072  0.064
3   Brazil  0.039  0.041  0.048  0.059  0.077  0.080  0.075  0.077
4    LISCR  0.039  0.040  0.044  0.047  0.051  0.060  0.055  0.064
5   Direct  0.040  0.041  0.043  0.046  0.049  0.050  0.050  0.051

### 3.4.2 Costs per Scenario relative to BAU

In [13]:
print("\nTotal FEM costs by scenario (US$)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:

    d_temp = {"20{0}".format(year): [
        np.round((trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        np.round((trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_usd_bau_{1}.csv".format(iso_country, version), index=False)
display(df)


print("\nTotal change in FEM costs by scenario (% bau)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    
    d_temp = {"20{0}".format(year): [
        round((100 * (trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex["bau_usd_{0}".format(year)].sum()), 2),
        round((100 * (trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex["bau_usd_{0}".format(year)].sum()), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_pct_bau_{1}.csv".format(iso_country, version), index=False)
display(df)


if res_mlc == True:
    print("\nTotal FEM costs by scenario (% ciffob)...\n")
    d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * (trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * (trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * (trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * (trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_ciffob.sum(), 2),
            round(100 * (trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_ciffob.sum(), 2),
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_pct_ciffob_{1}.csv".format(iso_country, version), index=False)
    display(df)


if res_mlc == True:
    print("\nTotal FEM costs by scenario (% cif)...\n")
    d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
    for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
        d_temp = {"20{0}".format(year): [
            round(100 * (trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * (trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * (trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * (trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_cifvalue.sum(), 2),
            round(100 * (trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.TandT_cifvalue.sum(), 2),
        ]}
        d = d | d_temp
    df = pd.DataFrame(data=d)
    df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_pct_cif_{1}.csv".format(iso_country, version), index=False)
    display(df)


print("\nTotal FEM costs by scenario (% fob)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * (trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.fobvalue.sum(), 2),
        round(100 * (trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.fobvalue.sum(), 2),
        round(100 * (trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.fobvalue.sum(), 2),
        round(100 * (trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.fobvalue.sum(), 2),
        round(100 * (trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / trade_ex.fobvalue.sum(), 2),
    ]}
    d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_pct_fob_{1}.csv".format(iso_country, version), index=False)
display(df)


print("\nTotal FEM costs by scenario (% gdp)...\n")
d = {"Scenario":["Levy", "'as-is'", "Brazil", "LISCR", "Direct"]}
for year in ["29", "32", "35", "38", "41", "44", "47", "50"]:
    d_temp = {"20{0}".format(year): [
        round(100 * (trade_ex["levy_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_ex["asis_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_ex["brazil_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_ex["liscr_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / gdp, 3),
        round(100 * (trade_ex["direct_usd_{0}".format(year)].sum() - trade_ex["bau_usd_{0}".format(year)].sum()) / gdp, 3),
    ]}
    d = d | d_temp

df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/results/impact_ex_costs_to_bau_pct_gdp_{1}.csv".format(iso_country, version), index=False)
display(df)

Total FEM costs by scenario (US$)...

,Scenario,2029,2032,2035,2038,2041,2044,2047,2050
0,Levy,541886.27,527325.61,657367.91,749903.56,789462.12,772194.21,623863.87,536276.23
1,'as-is',64468.08,122833.18,330232.59,500810.17,734482.47,700950.80,683822.68,552063.17
2,Brazil,17575.87,58280.20,206701.64,420666.67,751582.09,821267.49,743245.93,790701.41
3,LISCR,19615.04,40725.76,140537.59,209018.26,286937.89,469586.37,383657.48,558873.34
4,Direct,36058.76,74170.31,119220.44,188560.54,243529.16,272591.61,295139.23,313598.59

Total change in FEM costs by scenario (% bau)...

  Scenario   2029   2032   2035    2038    2041    2044    2047    2050
0     Levy  78.51  78.06  99.20  115.37  123.82  123.57  101.77   89.26
1  'as-is'   9.34  18.18  49.84   77.05  115.20  112.17  111.55   91.88
2   Brazil   2.55   8.63  31.19   64.72  117.88  131.42  121.25  131.60
3    LISCR   2.84   6.03  21.21   32.16   45.00   75.14   62.59   93.02
4   Direct   5.22  10.98  17.99   29.01   38.20   43.62   48.15   52.19

Total FEM costs by scenario (% fob)...

  Scenario   2029   2032   2035   2038   2041   2044   2047   2050
0     Levy  16.56  16.11  20.09  22.92  24.12  23.60  19.06  16.39
1  'as-is'   1.97   3.75  10.09  15.30  22.44  21.42  20.90  16.87
2   Brazil   0.54   1.78   6.32  12.85  22.97  25.10  22.71  24.16
3    LISCR   0.60   1.24   4.29   6.39   8.77  14.35  11.72  17.08
4   Direct   1.10   2.27   3.64   5.76   7.44   8.33   9.02   9.58

Total FEM costs by scenario (% gdp)...

  Scenario   2029   2032   2035   2038   2041   2044   2047   2050
0     Levy  0.030  0.029  0.036  0.041  0.044  0.043  0.034  0.030
1  'as-is'  0.004  0.007  0.018  0.028  0.041  0.039  0.038  0.031
2   Brazil  0.001  0.003  0.011  0.023  0.042  0.045  0.041  0.044
3    LISCR  0.001  0.002  0.008  0.012  0.016  0.026  0.021  0.031
4   Direct  0.002  0.004  0.007  0.010  0.013  0.015  0.016  0.017