<h2>Food (v0.03) - 'Food (v0.03).ipynb'</h2>

<u><h5>Context</h5></u>

The notebook aims to isolate NZF impacts modelled for individual commodities with 'CPC' codes forwarded over by David Forengie on 23rd September 2026.

The objectives of the notebook are:

<ol>
    <li>
        To develop the representation of CPC codes provided by David, as its not completely clear how these work (e.g. where some CPC codes are only 3 digits, whereas others are 5). 
    </li>
    <li>
        To read-in 'v0.64' of the 'Impact' analysis results for the country in question, then isolate these records for the CPC codes identified in the step above.
    </li>
</ol>

<u><h5>Version Documentation</h5></u>

'v0.01' outlined an initial method for completing the process. 'v0.02' refined the method and developed a fully functioning notebook, utilising results from the 'Impact' notebooks which now include CPC codes as fields in the output data tables. Upon inspection, it was found that the identification of CPC codes wasn't functioning properly, where CPC codes specified by David wouldn't show in the dataset, yet HSa4 codes given in the CPC manual would show. This likely explains much of the losses observed when pulling by CPC codes, so 'v0.03' utilises a new version of the codes sent through David which have been mapped to the HS system ahead of time.

In [1]:
# Import packages
import os
import base64
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', 250)
pd.set_option('display.max_rows', 250)
pd.options.mode.chained_assignment = None
from IPython.display import HTML
import matplotlib.pyplot as plt
import matplotlib.style
plt.style.use('seaborn-v0_8')

def download_link(df, title="Download CSV file", filename="data.csv"):
    csv = df.to_csv()
    b64 = base64.b64encode(csv.encode())
    payload = b64.decode()
    html = '<a download="{filename}" href="data:text/csv;base64,{payload}" target="_blank">{title}</a>'
    html = html.format(payload=payload,title=title,filename=filename)
    return HTML(html)

# define function for counting values in each data field
trade_im_field_count = lambda field: trade_im[field].value_counts().to_frame().reset_index()
trade_ex_field_count = lambda field: trade_ex[field].value_counts().to_frame().reset_index()

version = "v0.03"
input_dir = "/Users/apple/repos/PubEnv/2026_nzf_impact/"
output_dir = "/Users/apple/repos/PubEnv/2026_nzf_impact/food/"

# 1. Set up the notebook

## 1.1 Let's set the country we're interested in and set up a results folder.

In [2]:
# Select one of our countries to work on...
iso_code = "214"
iso_country = "Dominican Republic"
import_portfolio = "h6_ag6_by_sea_M*.csv" # Imports, '_M' | Foreign Imports, '_FM' | Re-Imports, '_RM'
export_portfolio = "h6_ag6_by_sea_X*.csv" # Exports, '_X' | Domestic Exports, '_DX' | Re-exports, '_RX'
year = 2025
gdp = 127.410*1e9

# Create output Journey directory folder if necessary
os.makedirs(output_dir+"{0}/".format(iso_country)) if not os.path.exists(output_dir+"{0}/".format(iso_country)) else "Output directory already exists."

## 1.2 Import and Format 'Impact Analysis' Results

In [3]:
impact_im_c = [
    "trade_idx", "reporterCode", "reporterDesc", "partnerCode", "partnerDesc", "flowDesc", "motDesc", 
    "HS6", "HS6_desc", "HS4", "HS4_desc", "HS2", "HS2_desc", "cpc", "cpc_desc", "eora_desc", "gtap", "gtap_desc", 
    "cifvalue", "fobvalue", "primaryValue", "qtyUnitAbbr", "qty", "netWgt", "vol_kg_vtw", 
    "sea_dist_km", "sea_dist_nm", "tnm", "fac_vessel_types", "fac_vessel_types_str", 
    #"TandT_match_desc", "TandT_ad_val_pct", "TandT_N", "TandT_ciffob", "TandT_cifvalue", "TandT_fobvalue", "cost_int_match_desc",
    "bau_usd_26", "levy_usd_26", "asis_usd_26", "brazil_usd_26", "liscr_usd_26", "direct_usd_26", 
    "bau_usd_29", "levy_usd_29", "asis_usd_29", "brazil_usd_29", "liscr_usd_29", "direct_usd_29", 
    "bau_usd_32", "levy_usd_32", "asis_usd_32", "brazil_usd_32", "liscr_usd_32", "direct_usd_32", 
    "bau_usd_35", "levy_usd_35", "asis_usd_35", "brazil_usd_35", "liscr_usd_35", "direct_usd_35", 
    "bau_usd_38", "levy_usd_38", "asis_usd_38", "brazil_usd_38", "liscr_usd_38", "direct_usd_38", 
    "bau_usd_41", "levy_usd_41", "asis_usd_41", "brazil_usd_41", "liscr_usd_41", "direct_usd_41", 
    "bau_usd_44", "levy_usd_44", "asis_usd_44", "brazil_usd_44", "liscr_usd_44", "direct_usd_44", 
    "bau_usd_47", "levy_usd_47", "asis_usd_47", "brazil_usd_47", "liscr_usd_47", "direct_usd_47", 
    "bau_usd_50", "levy_usd_50", "asis_usd_50", "brazil_usd_50", "liscr_usd_50", "direct_usd_50"	
]

impact_im_d = {
    "reporterCode":"str", "partnerCode":"str", 
    "HS6":"str", "HS4":"str", "HS2":"str", "HS2":"str", "gtap":"str", "cpc":"str"
}

impact_im = pd.read_csv(
    input_dir + "impact/{0}/impact_im_v0.64.csv".format(iso_country), 
    dtype=impact_im_d,
    usecols=impact_im_c
)[impact_im_c]

print("Aggregate trade portfolio statistics for '{0}': \n".format(iso_country))
print("Number of trade records present in dataset: {0}".format(impact_im.shape[0]))
print("Number of partner countries present in dataset: {0}".format(len(impact_im.partnerCode.unique())))
print("Modes of transport present in dataset: {0}".format(impact_im.motDesc.unique()))
print("Total value within the dataset: US${0}m".format(np.round(impact_im.cifvalue.sum() / 1e6, 1)))
print("Total weight within the dataset: {0} million kilograms".format(np.round(impact_im.vol_kg_vtw.sum() / 1e6, 1)))

impact_im["cpc_cl"] = [str(i).split('.')[0] for i in impact_im.cpc.values]
impact_im = impact_im.drop(columns="trade_idx").reset_index(drop=True).reset_index().rename(columns={"index":"trade_idx"})
display(impact_im.head(2))

Aggregate trade portfolio statistics for 'Dominican Republic':

Number of trade records present in dataset: 43923
Number of partner countries present in dataset: 186
Modes of transport present in dataset: ['Sea']
Total value within the dataset: US$27399.6m
Total weight within the dataset: 24564.0 million kilograms

,trade_idx,reporterCode,reporterDesc,partnerCode,partnerDesc,flowDesc,motDesc,HS6,HS6_desc,HS4,HS4_desc,HS2,HS2_desc,cpc,cpc_desc,eora_desc,gtap,gtap_desc,cifvalue,fobvalue,primaryValue,qtyUnitAbbr,qty,netWgt,vol_kg_vtw,sea_dist_km,sea_dist_nm,tnm,fac_vessel_types,fac_vessel_types_str,bau_usd_26,levy_usd_26,asis_usd_26,brazil_usd_26,liscr_usd_26,direct_usd_26,bau_usd_29,levy_usd_29,asis_usd_29,brazil_usd_29,liscr_usd_29,direct_usd_29,bau_usd_32,levy_usd_32,asis_usd_32,brazil_usd_32,liscr_usd_32,direct_usd_32,bau_usd_35,levy_usd_35,asis_usd_35,brazil_usd_35,liscr_usd_35,direct_usd_35,bau_usd_38,levy_usd_38,asis_usd_38,brazil_usd_38,liscr_usd_38,direct_usd_38,bau_usd_41,levy_usd_41,asis_usd_41,brazil_usd_41,liscr_usd_41,direct_usd_41,bau_usd_44,levy_usd_44,asis_usd_44,brazil_usd_44,liscr_usd_44,direct_usd_44,bau_usd_47,levy_usd_47,asis_usd_47,brazil_usd_47,liscr_usd_47,direct_usd_47,bau_usd_50,levy_usd_50,asis_usd_50,brazil_usd_50,liscr_usd_50,direct_usd_50,cpc_cl
0,0,214,Dominican Rep.,032,Argentina,Import,Sea,10121,"010121 | Horses; live, pure-b",0101,"0101 | Horses, asses, mules",01,01 | Animals; live,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,u,0.0,0.0,0.0,10138.0,6299.459198,0.0,['Container'],['Container'],0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,nan
1,1,214,Dominican Rep.,170,Colombia,Import,Sea,10121,"010121 | Horses; live, pure-b",0101,"0101 | Horses, asses, mules",01,01 | Animals; live,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,u,0.0,0.0,0.0,1431.0,889.181901,0.0,['Container'],['Container'],0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,nan

# 2. Subset the 'Impact Analysis' results for food security-related CPC codes

## 2.1 Let's get a sense of how much of import value is associated with food-relevant goods across classification systems

### 2.1.1 Harmonised System (HS01-23)

In [4]:
#print("HS groupings: \n\n{0}\n".format(pd.Series(impact_im.HS2_desc.unique()).sort_values().values))
HSa2_good_groups = [
    "01", "02", "03", "04", "05", "07", "08", # "06", 
    "09", "10", "11", "12", "13", "14", "15", "16", 
    "17", "18", "19", "20", "21", "22", "23"
]

impact_im_HSa2_food = impact_im[(impact_im.HS2.isin(HSa2_good_groups))]
impact_im_HSa2_food_g = impact_im_HSa2_food.groupby(["HS2_desc"]).agg({"cifvalue":"sum", "vol_kg_vtw":"sum"}).sort_values(by="cifvalue", ascending=False)
impact_im_HSa2_food_g["pct_val"] = round(100 * impact_im_HSa2_food_g.cifvalue / impact_im.cifvalue.sum(), 1)
impact_im_HSa2_food_g["pct_vol"] = round(100 * impact_im_HSa2_food_g.vol_kg_vtw / impact_im.vol_kg_vtw.sum(), 1)

print("Value of food imports identified via HSa2 ('Fishing' and 'Food & Beverages'): ${0}m ({1}%), ... \n\n{2}\n".format(
    round(impact_im_HSa2_food.cifvalue.sum() / 1e6, 1), 
    round(100 * impact_im_HSa2_food.cifvalue.sum() / impact_im.cifvalue.sum(), 1),
    impact_im_HSa2_food_g.round(1)
))

Value of food imports identified via HSa2 ('Fishing' and 'Food & Beverages'): $4870.2m (17.8%), ...

                              cifvalue    vol_kg_vtw  pct_val  pct_vol
HS2_desc
10 | Cereals               623873497.1  2.438682e+09      2.3      9.9
02 | Meat and edible meat  498884555.1  1.960089e+08      1.8      0.8
22 | Beverages, spirits a  498193965.4  8.141684e+08      1.8      3.3
04 | Dairy produce; birds  487711089.6  1.920844e+08      1.8      0.8
19 | Preparations of cere  366003681.7  1.238479e+08      1.3      0.5
15 | Animal, vegetable or  358325286.0  3.373327e+08      1.3      1.4
21 | Miscellaneous edible  321169973.5  8.117456e+07      1.2      0.3
03 | Fish and crustaceans  243114843.5  4.276750e+07      0.9      0.2
20 | Preparations of vege  235045604.3  1.569714e+08      0.9      0.6
07 | Vegetables and certa  182716397.6  2.857093e+08      0.7      1.2
12 | Oil seeds and oleagi  180313196.7  2.860601e+08      0.7      1.2
23 | Food industries, res  170322818.3  2.453794e+08      0.6      1.0
08 | Fruit and nuts, edib  159031240.3  1.176712e+08      0.6      0.5
09 | Coffee, tea, mate an  158682459.1  4.060516e+07      0.6      0.2
16 | Meat, fish, crustace  145256014.4  3.157610e+07      0.5      0.1
17 | Sugars and sugar con  106729897.9  1.000927e+08      0.4      0.4
11 | Products of the mill   60881192.1  1.102641e+08      0.2      0.4
18 | Cocoa and cocoa prep   50168335.6  1.107267e+07      0.2      0.0
13 | Lac; gums, resins an   18434893.0  2.043964e+06      0.1      0.0
05 | Animal originated pr    3936963.9  1.373274e+06      0.0      0.0
14 | Vegetable plaiting m    1375072.4  4.230640e+06      0.0      0.0
01 | Animals; live             58710.5  1.519780e+04      0.0      0.0

### 2.1.2 EORA groupings ('Food & Beverages' and 'Fishing')

In [5]:
print("EORA groupings: \n\n{0}\n".format(pd.Series(impact_im.eora_desc.unique()).sort_values().values))
eora_good_groups = ["Food & Beverages", "Agriculture", "Fishing"]

impact_im_eora_food = impact_im[(impact_im.eora_desc.isin(eora_good_groups))]
impact_im_eora_food_g = impact_im_eora_food.groupby(["eora_desc"]).agg({"cifvalue":"sum", "vol_kg_vtw":"sum"}).sort_values(by="cifvalue", ascending=False)
impact_im_eora_food_g["pct_val"] = round(100 * impact_im_eora_food_g.cifvalue / impact_im.cifvalue.sum(), 1)
impact_im_eora_food_g["pct_vol"] = round(100 * impact_im_eora_food_g.vol_kg_vtw / impact_im.vol_kg_vtw.sum(), 1)

print("Value of food imports identified via EORA ('Fishing' and 'Food & Beverages'): ${0}m ({1}%), ... \n\n{2}\n".format(
    round(impact_im_eora_food.cifvalue.sum() / 1e6, 1), 
    round(100 * impact_im_eora_food.cifvalue.sum() / impact_im.cifvalue.sum(), 1),
    impact_im_eora_food_g.round(1)
))

EORA groupings:

['Agriculture' 'Electrical and Machinery' 'Fishing' 'Food & Beverages'
 'Metal Products' 'Mining and Quarrying' 'Other Manufacturing'
 'Petroleum, Chemical and Non-Metallic Mineral Products'
 'Textiles and Wearing Apparel' 'Transport Equipment' 'Wood and Paper' nan]

Value of food imports identified via EORA ('Fishing' and 'Food & Beverages'): $4796.8m (17.5%), ...

                      cifvalue    vol_kg_vtw  pct_val  pct_vol
eora_desc
Agriculture       2.475758e+09  3.306568e+09      9.0     13.5
Food & Beverages  2.176239e+09  1.470718e+09      7.9      6.0
Fishing           1.447701e+08  2.032034e+07      0.5      0.1

### 2.1.3 GTAP (16x headings)

In [6]:
#print("GTAP groupings: \n\n{0}\n".format(pd.Series(impact_im.gtap_desc.unique()).sort_values().values))
gtap_food_groups = [
    "GRO - Cereal grains n.e.c.", "PDR - Paddy rice", "PCR - Processed rice", "SGR - Sugar", 
    "CMT - Bovine meat prods", "CTL - Bovine cattle, sheep and goats, horses", "FSH - Fishing", "OMT - Meat products n.e.c.",
    "MIL - Dairy products", "OFD - Food products n.e.c.", "V_F - Vegetables, fruit, nuts", "OSD - Oil seeds", 
    "OCR - Crops n.e.c.", "PFB - Plant-based fibers", "VOL - Vegetable oils and fats", 
    "OAP - Animal products n.e.c."
]

impact_im_gtap_food = impact_im[(impact_im.gtap_desc.isin(gtap_food_groups))]
impact_im_gtap_food_g = impact_im_gtap_food.groupby(["gtap_desc"]).agg({"cifvalue":"sum", "vol_kg_vtw":"sum"}).sort_values(by="cifvalue", ascending=False)
impact_im_gtap_food_g["pct_val"] = round(100 * impact_im_gtap_food_g.cifvalue / impact_im.cifvalue.sum(), 1)
impact_im_gtap_food_g["pct_vol"] = round(100 * impact_im_gtap_food_g.vol_kg_vtw / impact_im.vol_kg_vtw.sum(), 1)

print("Value of food imports identified via GTAP: ${0}m ({1}%), ... \n\n{2}\n".format(
    round(impact_im_gtap_food.cifvalue.sum() / 1e6, 1), 
    round(100 * impact_im_gtap_food.cifvalue.sum() / impact_im.cifvalue.sum(), 1),
    impact_im_gtap_food_g.head(15).round(1)
))

Value of food imports identified via GTAP: $4355.3m (15.9%), ...

                                                  cifvalue    vol_kg_vtw  \
gtap_desc
OFD - Food products n.e.c.                    1.442328e+09  5.757402e+08
OCR - Crops n.e.c.                            5.638760e+08  1.286740e+08
VOL - Vegetable oils and fats                 5.548056e+08  7.477441e+08
MIL - Dairy products                          4.743724e+08  1.760710e+08
OMT - Meat products n.e.c.                    4.483783e+08  1.806596e+08
GRO - Cereal grains n.e.c.                    4.292706e+08  1.772550e+09
V_F - Vegetables, fruit, nuts                 2.925647e+08  3.679662e+08
CMT - Bovine meat prods                       1.097647e+08  2.891954e+07
PCR - Processed rice                          2.033463e+07  3.532125e+07
SGR - Sugar                                   8.875495e+06  1.952718e+07
OAP - Animal products n.e.c.                  5.440460e+06  1.319063e+06
OSD - Oil seeds                               1.983936e+06  2.324337e+06
PFB - Plant-based fibers                      1.632428e+06  2.085606e+06
FSH - Fishing                                 1.413984e+06  2.553103e+05
CTL - Bovine cattle, sheep and goats, horses  1.700487e+05  1.770509e+05

                                              pct_val  pct_vol
gtap_desc
OFD - Food products n.e.c.                        5.3      2.3
OCR - Crops n.e.c.                                2.1      0.5
VOL - Vegetable oils and fats                     2.0      3.0
MIL - Dairy products                              1.7      0.7
OMT - Meat products n.e.c.                        1.6      0.7
GRO - Cereal grains n.e.c.                        1.6      7.2
V_F - Vegetables, fruit, nuts                     1.1      1.5
CMT - Bovine meat prods                           0.4      0.1
PCR - Processed rice                              0.1      0.1
SGR - Sugar                                       0.0      0.1
OAP - Animal products n.e.c.                      0.0      0.0
OSD - Oil seeds                                   0.0      0.0
PFB - Plant-based fibers                          0.0      0.0
FSH - Fishing                                     0.0      0.0
CTL - Bovine cattle, sheep and goats, horses      0.0      0.0

## 2.2 Comparison of results

In [7]:
print("Share of total import value associated with food-relevant goods by classification system...\n\nHSa2 {0}% \nGTAP {1}% \nEORA {2}%".format(
    round(100 * impact_im_HSa2_food.cifvalue.sum() / impact_im.cifvalue.sum(), 1),
    round(100 * impact_im_gtap_food.cifvalue.sum() / impact_im.cifvalue.sum(), 1),
    round(100 * impact_im_eora_food.cifvalue.sum() / impact_im.cifvalue.sum(), 1)
))

Share of total import value associated with food-relevant goods by classification system...

HSa2 17.8%
GTAP 15.9%
EORA 17.5%

# 3. Take HSa4 codes associated with specific CPCs

## 3.1 Set HSa4 Codes we're interested in

In [8]:
hsa4_codes_food = {
    "Dairy": [
        "0401", "0402", "0403", "0404", "0405", "0406",
    ],
    "Fats and Oils": [
        "1501", "1502", "1503", "1504", "1505", "1506", "1507", "1508", "1509", "1510"
        "1511", "1512", "1513", "1514", "1515", "1516", "1517"
    ],
    "Fruits": [
        "0709", "0801", "0802", "0803", "0804", "0805", "0806", "0807", "0808", "0809", 
        "0810", "0813", "2009"
    ],
    "Meat and Prep": [
        "0201", "0203", "0204", "0205", "0207", "0208", "0209", "2301"
    ],
    "Processed Cereals": [
        "1006", "1101", "1102", "1104", "1105", "1106", "1107", "1108", "1109", "1302",
        "1602", "1901", "1902", "1903", "1904", "1905", "2005", "2007", "2104", "2106", 
        "3505"
    ],
    "Sugar and Honey": [
        "1701", "1702", "1703", "1704", "2006"
    ],
    "Unprocessed Cereals": [
        "1001", "1002", "1003", "1004", "1005", "1007", "1008"
    ],
    "Vegetables": [
        "0701", "0702", "0703", "0704", "0705", "0706", "0707", "0708", "0709", "0710",
        "0712", "0713", "0714", "1209", "2009"
    ]
}

## 3.2 Identify 'Food Security' groups of interest via CPC

In [9]:
impact_im["food_group"] = np.nan

for food_group in list(hsa4_codes_food.keys()):
    impact_im.loc[impact_im.HS4.isin(hsa4_codes_food[food_group]), "food_group"] = food_group

display(impact_im.head(2))

/var/folders/_k/81z8ryjd28lc4f0bb4dm7gkw0000gn/T/ipykernel_23075/1412186970.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Dairy' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  impact_im.loc[impact_im.HS4.isin(hsa4_codes_food[food_group]), "food_group"] = food_group

,trade_idx,reporterCode,reporterDesc,partnerCode,partnerDesc,flowDesc,motDesc,HS6,HS6_desc,HS4,HS4_desc,HS2,HS2_desc,cpc,cpc_desc,eora_desc,gtap,gtap_desc,cifvalue,fobvalue,primaryValue,qtyUnitAbbr,qty,netWgt,vol_kg_vtw,sea_dist_km,sea_dist_nm,tnm,fac_vessel_types,fac_vessel_types_str,bau_usd_26,levy_usd_26,asis_usd_26,brazil_usd_26,liscr_usd_26,direct_usd_26,bau_usd_29,levy_usd_29,asis_usd_29,brazil_usd_29,liscr_usd_29,direct_usd_29,bau_usd_32,levy_usd_32,asis_usd_32,brazil_usd_32,liscr_usd_32,direct_usd_32,bau_usd_35,levy_usd_35,asis_usd_35,brazil_usd_35,liscr_usd_35,direct_usd_35,bau_usd_38,levy_usd_38,asis_usd_38,brazil_usd_38,liscr_usd_38,direct_usd_38,bau_usd_41,levy_usd_41,asis_usd_41,brazil_usd_41,liscr_usd_41,direct_usd_41,bau_usd_44,levy_usd_44,asis_usd_44,brazil_usd_44,liscr_usd_44,direct_usd_44,bau_usd_47,levy_usd_47,asis_usd_47,brazil_usd_47,liscr_usd_47,direct_usd_47,bau_usd_50,levy_usd_50,asis_usd_50,brazil_usd_50,liscr_usd_50,direct_usd_50,cpc_cl,food_group
0,0,214,Dominican Rep.,032,Argentina,Import,Sea,10121,"010121 | Horses; live, pure-b",0101,"0101 | Horses, asses, mules",01,01 | Animals; live,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,u,0.0,0.0,0.0,10138.0,6299.459198,0.0,['Container'],['Container'],0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,nan,NaN
1,1,214,Dominican Rep.,170,Colombia,Import,Sea,10121,"010121 | Horses; live, pure-b",0101,"0101 | Horses, asses, mules",01,01 | Animals; live,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,u,0.0,0.0,0.0,1431.0,889.181901,0.0,['Container'],['Container'],0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,nan,NaN

## 3.3 Inspect the output

In [10]:
impact_im_cpc_food = impact_im[(~impact_im.food_group.isna())]
impact_im_cpc_food_g = impact_im_cpc_food.groupby("food_group").agg({"HS6_desc":"count", "cifvalue":"sum", "vol_kg_vtw":"sum"}).reset_index().sort_values(by="cifvalue", ascending=False).round(2).rename(columns={"HS6_desc":"N_com"}).reset_index(drop=True)
impact_im_cpc_food_g["pct_val"] = round(100 * impact_im_cpc_food_g.cifvalue / impact_im.cifvalue.sum(), 1)
impact_im_cpc_food_g["pct_vol"] = round(100 * impact_im_cpc_food_g.vol_kg_vtw / impact_im.vol_kg_vtw.sum(), 1)

print("Proportion of imports identified as food security-relevant:\n")
print("Value: ${0}m of ${1}m ({2}%)".format(
    round(impact_im_cpc_food.cifvalue.sum() / 1e6, 1),
    round(impact_im.cifvalue.sum() / 1e6, 1),
    round(100 * impact_im_cpc_food.cifvalue.sum() / impact_im.cifvalue.sum(), 1)
))
print("Volume: {0} of {1} million kilograms ({2}%)".format(
    round(impact_im_cpc_food.vol_kg_vtw.sum() / 1e6, 1),
    round(impact_im.vol_kg_vtw.sum() / 1e6, 1),
    round(100 * impact_im_cpc_food.vol_kg_vtw.sum() / impact_im.vol_kg_vtw.sum(), 1)
))
print("Value-to-Weight: {0} from {1} US$ per kg (+{2}%)".format(
    round(impact_im_cpc_food.cifvalue.sum() / impact_im_cpc_food.vol_kg_vtw.sum(), 2),
    round(impact_im.cifvalue.sum() / impact_im.vol_kg_vtw.sum(), 2),
    round(100 * ((impact_im_cpc_food.cifvalue.sum() / impact_im_cpc_food.vol_kg_vtw.sum()) - (impact_im.cifvalue.sum() / impact_im.vol_kg_vtw.sum())) / (impact_im.cifvalue.sum() / impact_im.vol_kg_vtw.sum()), 1)
))
print("Average distance to market (volume-weighted): {0} from {1} nm (+{2}%)".format(
    round((impact_im_cpc_food.vol_kg_vtw / 1000 * impact_im_cpc_food.sea_dist_nm).sum() / (impact_im_cpc_food.vol_kg_vtw.sum() / 1000), 1),
    round((impact_im.vol_kg_vtw / 1000 * impact_im.sea_dist_nm).sum() / (impact_im.vol_kg_vtw.sum() / 1000), 1),
    round(100 * (((impact_im_cpc_food.vol_kg_vtw / 1000 * impact_im_cpc_food.sea_dist_nm).sum() / (impact_im_cpc_food.vol_kg_vtw.sum() / 1000)) - ((impact_im.vol_kg_vtw / 1000 * impact_im.sea_dist_nm).sum() / (impact_im.vol_kg_vtw.sum() / 1000))) / \
          ((impact_im.vol_kg_vtw / 1000 * impact_im.sea_dist_nm).sum() / (impact_im.vol_kg_vtw.sum() / 1000)), 1)
))
print("\n{0}\n".format(impact_im_cpc_food_g.head(15).round(1)))

impact_im_cpc_food_g.to_csv(output_dir + "{0}/food_total_usd_{1}.csv".format(iso_country, version), index=False)

Proportion of imports identified as food security-relevant:

Value: $3074.2m of $27399.6m (11.2%)
Volume: 3917.5 of 24564.0 million kilograms (15.9%)
Value-to-Weight: 0.78 from 1.12 US$ per kg (+-29.6%)
Average distance to market (volume-weighted): 3097.2 from 3233.5 nm (+-4.2%)

            food_group  N_com     cifvalue    vol_kg_vtw  pct_val  pct_vol
0    Processed Cereals    653  818844187.3  3.669042e+08      3.0      1.5
1  Unprocessed Cereals     27  603453310.2  2.403212e+09      2.2      9.8
2                Dairy    135  482567341.3  1.892924e+08      1.8      0.8
3        Meat and Prep     62  400019680.2  1.780853e+08      1.5      0.7
4        Fats and Oils    119  266421625.6  2.331816e+08      1.0      0.9
5           Vegetables    310  248633312.5  3.342244e+08      0.9      1.4
6               Fruits    139  147488360.2  1.125093e+08      0.5      0.5
7      Sugar and Honey    128  106772697.5  1.001050e+08      0.4      0.4

## 3.3 Derive results for 2029, 2041 and 2050

### 3.3.1 Total FEM costs by scenario (US$)

In [11]:
print("\nTotal FEM costs by scenario (US$)...\n")

d = {"food_group": list(hsa4_codes_food.keys())}
for year in ["29", "41", "50"]:
    for scenario in ["bau", "levy", "asis", "brazil", "liscr", "direct"]:
        d_temp = {
            "{0}_{1}".format(scenario, year): [
            round(100 * impact_im[(impact_im.food_group == hsa4_codes_food_key)]["{0}_usd_{1}".format(scenario, year)].sum(), 1) \
                    for hsa4_codes_food_key in list(hsa4_codes_food.keys())]}
        d = d | d_temp
df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/food_total_costs_usd_{1}.csv".format(iso_country, version), index=False)
display(df)

Total FEM costs by scenario (US$)...

,food_group,bau_29,levy_29,asis_29,brazil_29,liscr_29,direct_29,bau_41,levy_41,asis_41,brazil_41,liscr_41,direct_41,bau_50,levy_50,asis_50,brazil_50,liscr_50,direct_50
0,Dairy,2.100321e+08,3.888564e+08,2.305050e+08,2.139299e+08,2.147291e+08,2.207004e+08,1.928493e+08,4.531083e+08,4.357624e+08,4.351341e+08,2.817525e+08,2.701907e+08,1.807084e+08,3.489350e+08,3.568286e+08,4.277335e+08,3.473397e+08,2.807326e+08
1,Fats and Oils,4.107511e+08,6.684805e+08,4.378062e+08,4.106633e+08,4.118300e+08,4.263697e+08,3.856463e+08,7.538273e+08,7.285095e+08,7.511584e+08,5.243053e+08,4.983367e+08,3.680756e+08,6.234834e+08,6.390923e+08,7.434468e+08,6.166370e+08,5.135467e+08
2,Fruits,9.649219e+07,1.776324e+08,1.057283e+08,9.821103e+07,9.857677e+07,1.013303e+08,8.869501e+07,2.069707e+08,1.989119e+08,1.989483e+08,1.291110e+08,1.237904e+08,8.318526e+07,1.597660e+08,1.633857e+08,1.955418e+08,1.588777e+08,1.286167e+08
3,Meat and Prep,1.115898e+08,2.068615e+08,1.225094e+08,1.136773e+08,1.141031e+08,1.172736e+08,1.024351e+08,2.410499e+08,2.318546e+08,2.314489e+08,1.497915e+08,1.436351e+08,9.596801e+07,1.855309e+08,1.897200e+08,2.275068e+08,1.847118e+08,1.492400e+08
4,Processed Cereals,4.706014e+08,8.648337e+08,5.154000e+08,4.788789e+08,4.806593e+08,4.941060e+08,4.327162e+08,1.007769e+09,9.683636e+08,9.689642e+08,6.292938e+08,6.032358e+08,4.059444e+08,7.784447e+08,7.960683e+08,9.522694e+08,7.739175e+08,6.267266e+08
5,Sugar and Honey,8.897127e+07,1.501186e+08,9.529471e+07,8.955292e+07,8.984877e+07,9.261738e+07,8.306348e+07,1.775916e+08,1.697851e+08,1.729144e+08,1.171929e+08,1.094836e+08,7.890070e+07,1.411664e+08,1.437950e+08,1.676822e+08,1.391270e+08,1.130880e+08
6,Unprocessed Cereals,2.458592e+09,4.474375e+09,2.685870e+09,2.498440e+09,2.507555e+09,2.578872e+09,2.264690e+09,5.231835e+09,5.028192e+09,5.037231e+09,3.291600e+09,3.136055e+09,2.127820e+09,4.051299e+09,4.138723e+09,4.936423e+09,4.025780e+09,3.253829e+09
7,Vegetables,3.918720e+08,7.230096e+08,4.296484e+08,3.989646e+08,4.004530e+08,4.116201e+08,3.600523e+08,8.424617e+08,8.098675e+08,8.095132e+08,5.248851e+08,5.032703e+08,3.375683e+08,6.497033e+08,6.644074e+08,7.956684e+08,6.463269e+08,5.228957e+08

### 3.3.2 Total FEM costs by scenario (% cif)

In [12]:
print("\nTotal FEM costs by scenario (% cif)...\n")

d = {"food_group":list(hsa4_codes_food.keys())}
for year in ["29", "41", "50"]:
    for scenario in ["levy", "asis", "brazil", "liscr", "direct"]:
        d_temp = {
            "{0}_{1}".format(scenario, year): [
            np.round(100 * (impact_im[(impact_im.food_group == hsa4_codes_food_key)]["{0}_usd_{1}".format(scenario, year)].sum() - impact_im[(impact_im.food_group == hsa4_codes_food_key)]["bau_usd_{1}".format(scenario, year)].sum()) / \
                     impact_im[(impact_im.food_group == hsa4_codes_food_key)].cifvalue.sum(), 2) \
                    for hsa4_codes_food_key in list(hsa4_codes_food.keys())]}
        d = d | d_temp

df = pd.DataFrame(data=d)
df.to_csv(output_dir + "{0}/food_total_costs_pct_cif_{1}.csv".format(iso_country, version), index=False)
display(df)

Total FEM costs by scenario (% cif)...

,food_group,levy_29,asis_29,brazil_29,liscr_29,direct_29,levy_41,asis_41,brazil_41,liscr_41,direct_41,levy_50,asis_50,brazil_50,liscr_50,direct_50
0,Dairy,0.37,0.04,0.01,0.01,0.02,0.54,0.50,0.50,0.18,0.16,0.35,0.36,0.51,0.35,0.21
1,Fats and Oils,0.97,0.10,-0.00,0.00,0.06,1.38,1.29,1.37,0.52,0.42,0.96,1.02,1.41,0.93,0.55
2,Fruits,0.55,0.06,0.01,0.01,0.03,0.80,0.75,0.75,0.27,0.24,0.52,0.54,0.76,0.51,0.31
3,Meat and Prep,0.24,0.03,0.01,0.01,0.01,0.35,0.32,0.32,0.12,0.10,0.22,0.23,0.33,0.22,0.13
4,Processed Cereals,0.48,0.05,0.01,0.01,0.03,0.70,0.65,0.65,0.24,0.21,0.45,0.48,0.67,0.45,0.27
5,Sugar and Honey,0.57,0.06,0.01,0.01,0.03,0.89,0.81,0.84,0.32,0.25,0.58,0.61,0.83,0.56,0.32
6,Unprocessed Cereals,3.34,0.38,0.07,0.08,0.20,4.92,4.58,4.59,1.70,1.44,3.19,3.33,4.65,3.15,1.87
7,Vegetables,1.33,0.15,0.03,0.03,0.08,1.94,1.81,1.81,0.66,0.58,1.26,1.31,1.84,1.24,0.75